"""Pytest tests for the FSI-AgentGov Frontier Readiness Scoring Engine.

Covers score_driver(), detect_scale_breaker(), assess_pattern_readiness(),
compute_evaluator_coverage(), and the run() entry point.
Fixtures: frontier_answers_partial.json, frontier_answers_high.json,
          expected_frontier_scores.json (generated by score_frontier.py).
"""

import json
import sys
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Path setup — allow importing score_frontier.py from the engine directory
# ---------------------------------------------------------------------------

ASSESSMENT_ROOT = Path(__file__).resolve().parent.parent
ENGINE_DIR = ASSESSMENT_ROOT / "engine"
FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"
MANIFEST_PATH = ASSESSMENT_ROOT / "manifest" / "frontier-readiness.json"

sys.path.insert(0, str(ENGINE_DIR))

import score_frontier  # noqa: E402

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def load_fixture(name: str) -> dict:
    """Load a JSON fixture file by name from the fixtures directory."""
    path = FIXTURES_DIR / name
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def write_json(path: Path, data: dict) -> None:
    """Write *data* as indented JSON to *path*, creating parent dirs."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def setup_frontier_collected(
    tmp_path: Path,
    fixture_name: str = "frontier_answers_partial.json",
) -> Path:
    """Copy a frontier answers fixture into a temp collected/ dir for run()."""
    collected = tmp_path / "collected"
    collected.mkdir()
    data = load_fixture(fixture_name)
    write_json(collected / "frontier.json", data)
    return collected


def _make_question(
    question_id: str,
    driver: str,
    level: int,
    weight: float = 1.0,
    answer_format: str = "yes_no_partial",
) -> dict:
    """Build a minimal question dict for unit tests."""
    return {
        "question_id": question_id,
        "driver": driver,
        "level": level,
        "scoring_weight": weight,
        "answer_format": answer_format,
        "auto_evaluable": False,
        "collection_methods": ["Manual"],
    }


def _make_five_level_questions(driver: str) -> list[dict]:
    """One question per maturity level (100-500) for the given driver."""
    return [
        _make_question(f"TST_{level}", driver, level)
        for level in score_frontier.LEVELS
    ]


# ---------------------------------------------------------------------------
# Pytest fixtures
# ---------------------------------------------------------------------------


@pytest.fixture()
def manifest_data() -> dict:
    """The real 25-question manifest (loaded once per test)."""
    with open(MANIFEST_PATH, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture()
def partial_answers() -> dict:
    """Partial fixture: mixed answers producing predictable per-driver scores."""
    return load_fixture("frontier_answers_partial.json")


@pytest.fixture()
def high_answers() -> dict:
    """High fixture: all 25 questions answered 'yes' → all drivers score 500."""
    return load_fixture("frontier_answers_high.json")


# ---------------------------------------------------------------------------
# TestScoreDriver
# ---------------------------------------------------------------------------


class TestScoreDriver:
    """Unit tests for the score_driver() function."""

    @staticmethod
    def _yes_answers(questions: list[dict]) -> dict[str, dict]:
        return {q["question_id"]: {"value": "yes"} for q in questions}

    @staticmethod
    def _no_answers(questions: list[dict]) -> dict[str, dict]:
        return {q["question_id"]: {"value": "no"} for q in questions}

    def test_all_yes_produces_500(self) -> None:
        """All 5 questions answered yes → score 500, label 'Optimized', confidence high."""
        questions = _make_five_level_questions("ai_strategy")
        answers = self._yes_answers(questions)
        result = score_frontier.score_driver("ai_strategy", questions, answers)
        assert result["score"] == 500
        assert result["level_label"] == "Optimized"
        assert result["confidence"] == "high"
        assert result["questions_answered"] == 5

    def test_all_no_produces_low(self) -> None:
        """All 5 questions answered no → score 0, label 'Below Initial'."""
        questions = _make_five_level_questions("ai_strategy")
        answers = self._no_answers(questions)
        result = score_frontier.score_driver("ai_strategy", questions, answers)
        assert result["score"] == 0
        assert result["level_label"] == "Below Initial"
        assert result["confidence"] == "high"

    def test_partial_climbs_correctly(self) -> None:
        """L100=yes, L200=yes, L300=partial (ratio 0.5 < 0.7) → score 250, label 'Repeatable+'."""
        questions = _make_five_level_questions("ai_strategy")
        answers = {
            "TST_100": {"value": "yes"},
            "TST_200": {"value": "yes"},
            "TST_300": {"value": "partial"},
            # TST_400 and TST_500 intentionally absent
        }
        result = score_frontier.score_driver("ai_strategy", questions, answers)
        assert result["score"] == 250
        assert result["level_label"] == "Repeatable+"
        assert result["level_breakdown"]["300"]["ratio"] == pytest.approx(0.5)
        assert result["level_breakdown"]["100"]["ratio"] == pytest.approx(1.0)
        assert result["level_breakdown"]["200"]["ratio"] == pytest.approx(1.0)

    def test_missing_answers_lower_confidence(self) -> None:
        """3 of 5 questions unanswered → questions_answered=2, confidence 'low'."""
        questions = _make_five_level_questions("ai_strategy")
        # Only L400 and L500 answered; L100, L200, L300 absent
        answers = {
            "TST_400": {"value": "yes"},
            "TST_500": {"value": "yes"},
        }
        result = score_frontier.score_driver("ai_strategy", questions, answers)
        assert result["questions_answered"] == 2
        assert result["confidence"] == "low"

    def test_skip_threshold_blocks_advancement(self) -> None:
        """L100=partial (ratio 0.5 < 0.7) → highest_fully_achieved=0, score=50, label 'Below Initial'."""
        questions = _make_five_level_questions("ai_strategy")
        answers = {"TST_100": {"value": "partial"}}
        result = score_frontier.score_driver("ai_strategy", questions, answers)
        assert result["score"] == 50
        assert result["level_label"] == "Below Initial"
        assert result["level_breakdown"]["100"]["ratio"] == pytest.approx(0.5)

    def test_scale_1_5_format_normalizes(self) -> None:
        """scale_1_5 answer value=3 → normalized 0.5; below threshold → score 50."""
        question = _make_question("Q_SCALE", "ai_strategy", 100, answer_format="scale_1_5")
        result = score_frontier.score_driver("ai_strategy", [question], {"Q_SCALE": {"value": 3}})
        # (3-1)/4 = 0.5 < 0.7 → score = int(round(0.5*100)) = 50
        assert result["score"] == 50
        assert result["level_label"] == "Below Initial"
        assert result["level_breakdown"]["100"]["ratio"] == pytest.approx(0.5)

    def test_text_format_excluded_from_scoring(self) -> None:
        """text format answers are not auto-scored → questions_answered=0, score=0."""
        question = _make_question("Q_TEXT", "ai_strategy", 100, answer_format="text")
        result = score_frontier.score_driver(
            "ai_strategy", [question], {"Q_TEXT": {"value": "Some descriptive text"}}
        )
        assert result["questions_answered"] == 0
        assert result["score"] == 0

    def test_multiple_questions_per_level_weighted_average(self) -> None:
        """Two L100 questions (weight 1.0): one yes, one no → ratio 0.5 → score 50."""
        questions = [
            _make_question("Q_A", "ai_strategy", 100, 1.0),
            _make_question("Q_B", "ai_strategy", 100, 1.0),
        ]
        answers = {"Q_A": {"value": "yes"}, "Q_B": {"value": "no"}}
        result = score_frontier.score_driver("ai_strategy", questions, answers)
        assert result["level_breakdown"]["100"]["ratio"] == pytest.approx(0.5)
        assert result["score"] == 50
        assert result["level_label"] == "Below Initial"

    def test_level_breakdown_keys_always_present(self) -> None:
        """level_breakdown always has keys '100' through '500' regardless of answers."""
        questions = _make_five_level_questions("business_strategy")
        result = score_frontier.score_driver("business_strategy", questions, {})
        for level in ("100", "200", "300", "400", "500"):
            assert level in result["level_breakdown"]
            lb = result["level_breakdown"][level]
            assert "answered" in lb and "total" in lb and "ratio" in lb

    def test_no_questions_for_driver_returns_zero(self) -> None:
        """Driver with no questions in manifest → score 0, confidence 'low'."""
        result = score_frontier.score_driver("ai_strategy", [], {})
        assert result["score"] == 0
        assert result["questions_total"] == 0
        assert result["questions_answered"] == 0


# ---------------------------------------------------------------------------
# TestScaleBreaker
# ---------------------------------------------------------------------------


class TestScaleBreaker:
    """Unit tests for detect_scale_breaker()."""

    @staticmethod
    def _scores(**kwargs: int) -> dict[str, dict]:
        return {driver: {"score": score} for driver, score in kwargs.items()}

    def test_detects_lowest_driver(self) -> None:
        """Lowest-scoring driver is returned as scale_breaker.driver with correct score."""
        scores = self._scores(
            ai_strategy=300,
            business_strategy=150,
            ai_governance=400,
            technology_data=350,
            organization_culture=250,
        )
        result = score_frontier.detect_scale_breaker(scores)
        assert result["driver"] == "business_strategy"
        assert result["score"] == 150
        assert result["tied_with"] == []

    def test_handles_ties(self) -> None:
        """Two drivers tied at minimum: primary is first in DRIVER_IDS; second in tied_with."""
        scores = self._scores(
            ai_strategy=300,
            business_strategy=100,
            ai_governance=400,
            technology_data=350,
            organization_culture=100,
        )
        result = score_frontier.detect_scale_breaker(scores)
        assert result["driver"] == "business_strategy"
        assert result["score"] == 100
        assert "organization_culture" in result["tied_with"]
        assert "business_strategy" not in result["tied_with"]

    def test_canonical_order_for_5way_tie(self) -> None:
        """All 5 drivers tied → first in DRIVER_IDS is primary; remaining 4 in tied_with."""
        scores = self._scores(
            ai_strategy=200,
            business_strategy=200,
            ai_governance=200,
            technology_data=200,
            organization_culture=200,
        )
        result = score_frontier.detect_scale_breaker(scores)
        assert result["driver"] == "ai_strategy"
        assert result["score"] == 200
        assert len(result["tied_with"]) == 4
        assert result["tied_with"][0] == "business_strategy"

    def test_empty_driver_scores_returns_none(self) -> None:
        """Empty dict → driver=None, score=None, tied_with=[]."""
        result = score_frontier.detect_scale_breaker({})
        assert result["driver"] is None
        assert result["score"] is None
        assert result["tied_with"] == []

    def test_rationale_always_populated(self) -> None:
        """rationale field is always a non-empty string."""
        result = score_frontier.detect_scale_breaker(self._scores(ai_strategy=300))
        assert isinstance(result["rationale"], str)
        assert len(result["rationale"]) > 0


# ---------------------------------------------------------------------------
# TestPatternReadiness
# ---------------------------------------------------------------------------

# Minimal pattern targets: P1 (low bar), P6 (all 500)
_P1_P6_TARGETS = {
    "1": {
        "ai_strategy": 200,
        "business_strategy": 200,
        "ai_governance": 300,
        "technology_data": 300,
        "organization_culture": 300,
    },
    "6": {
        "ai_strategy": 500,
        "business_strategy": 500,
        "ai_governance": 500,
        "technology_data": 500,
        "organization_culture": 500,
    },
}


class TestPatternReadiness:
    """Unit tests for assess_pattern_readiness()."""

    @staticmethod
    def _scores(**kwargs: int) -> dict[str, dict]:
        return {driver: {"score": score} for driver, score in kwargs.items()}

    def test_pattern_1_ready_at_exact_threshold(self) -> None:
        """P1 needs 200/200/300/300/300; all exactly at threshold → ready=True, no gaps."""
        scores = self._scores(
            ai_strategy=200,
            business_strategy=200,
            ai_governance=300,
            technology_data=300,
            organization_culture=300,
        )
        result = score_frontier.assess_pattern_readiness(scores, _P1_P6_TARGETS)
        assert result["1"]["ready"] is True
        assert result["1"]["gap_drivers"] == []
        assert result["1"]["min_gap"] == 0

    def test_pattern_6_requires_500_across(self) -> None:
        """P6 needs all 500; score of 499 anywhere → not ready; all 500 → ready."""
        not_ready_scores = self._scores(
            ai_strategy=499,
            business_strategy=500,
            ai_governance=500,
            technology_data=500,
            organization_culture=500,
        )
        result = score_frontier.assess_pattern_readiness(not_ready_scores, _P1_P6_TARGETS)
        assert result["6"]["ready"] is False
        gap_drivers = result["6"]["gap_drivers"]
        assert any(g["driver"] == "ai_strategy" for g in gap_drivers)

        ready_scores = self._scores(
            ai_strategy=500,
            business_strategy=500,
            ai_governance=500,
            technology_data=500,
            organization_culture=500,
        )
        result_ready = score_frontier.assess_pattern_readiness(ready_scores, _P1_P6_TARGETS)
        assert result_ready["6"]["ready"] is True

    def test_min_gap_is_smallest_positive(self) -> None:
        """When multiple gap_drivers exist, min_gap is the smallest gap value."""
        # P1 targets: ai_strategy=200, business_strategy=200, ai_governance=300,
        #             technology_data=300, organization_culture=300
        scores = self._scores(
            ai_strategy=100,         # gap 100 to 200
            business_strategy=200,   # OK
            ai_governance=250,       # gap 50 to 300 ← smallest
            technology_data=200,     # gap 100 to 300
            organization_culture=200, # gap 100 to 300
        )
        result = score_frontier.assess_pattern_readiness(scores, _P1_P6_TARGETS)
        assert result["1"]["ready"] is False
        assert result["1"]["min_gap"] == 50

    def test_exceeding_target_counts_as_ready(self) -> None:
        """Scores above target threshold satisfy readiness — current >= target is sufficient."""
        scores = self._scores(
            ai_strategy=400,
            business_strategy=300,
            ai_governance=500,
            technology_data=400,
            organization_culture=350,
        )
        result = score_frontier.assess_pattern_readiness(scores, _P1_P6_TARGETS)
        assert result["1"]["ready"] is True

    def test_gap_driver_fields(self) -> None:
        """Each gap_driver dict has driver, current, target, gap keys."""
        scores = self._scores(
            ai_strategy=100,
            business_strategy=200,
            ai_governance=300,
            technology_data=300,
            organization_culture=300,
        )
        result = score_frontier.assess_pattern_readiness(scores, _P1_P6_TARGETS)
        assert result["1"]["ready"] is False
        gd = result["1"]["gap_drivers"][0]
        assert gd["driver"] == "ai_strategy"
        assert gd["current"] == 100
        assert gd["target"] == 200
        assert gd["gap"] == 100


# ---------------------------------------------------------------------------
# TestEvaluatorCoverage
# ---------------------------------------------------------------------------


class TestEvaluatorCoverage:
    """Unit tests for compute_evaluator_coverage()."""

    def test_v1_counts_after_q16_q17_wiring(self, manifest_data: dict) -> None:
        """Real frontier-readiness.json post-Q16/Q17/Q13/Q01/Q18/Q03: 6 auto, 19 manual, 0 unimplemented."""
        questions = manifest_data["questions"]
        coverage = score_frontier.compute_evaluator_coverage(questions)
        assert coverage["questions"]["auto_evaluable"] == 6
        assert coverage["questions"]["manual_only"] == 19
        assert coverage["questions"]["unimplemented_evaluator"] == 0
        assert coverage["total_questions"] == 25

    def test_auto_evaluable_requires_registered_evaluator(self) -> None:
        """auto_evaluable=True with unregistered pass_condition → unimplemented_evaluator."""
        questions = [
            {
                "question_id": "Q01",
                "auto_evaluable": True,
                "pass_condition": "nonexistent_evaluator",
                "collection_methods": ["Manual", "API"],
            },
            {"question_id": "Q02", "auto_evaluable": False, "collection_methods": ["Manual"]},
        ]
        coverage = score_frontier.compute_evaluator_coverage(questions)
        assert coverage["questions"]["auto_evaluable"] == 0
        assert coverage["questions"]["unimplemented_evaluator"] == 1
        assert coverage["questions"]["manual_only"] == 1

    def test_non_manual_without_evaluator_counted(self) -> None:
        """Collection method other than Manual, auto_evaluable False → unimplemented_evaluator."""
        questions = [
            {
                "question_id": "Q01",
                "auto_evaluable": False,
                "collection_methods": ["API", "Manual"],
            },
        ]
        coverage = score_frontier.compute_evaluator_coverage(questions)
        assert coverage["questions"]["unimplemented_evaluator"] == 1
        assert coverage["questions"]["manual_only"] == 0

    def test_empty_question_list(self) -> None:
        """Empty question list → all counts zero, total_questions zero."""
        coverage = score_frontier.compute_evaluator_coverage([])
        assert coverage["total_questions"] == 0
        assert all(v == 0 for v in coverage["questions"].values())


# ---------------------------------------------------------------------------
# TestEndToEnd
# ---------------------------------------------------------------------------

_REQUIRED_TOP_KEYS = frozenset(
    {"_metadata", "driver_scores", "scale_breaker", "pattern_readiness", "evaluator_coverage", "evaluator_results"}
)
_REQUIRED_METADATA_KEYS = frozenset({"engine_version", "timestamp", "manifest_version"})


class TestEndToEnd:
    """End-to-end tests calling run() with fixture data and the real manifest."""

    def test_run_produces_valid_summary(self, tmp_path: Path) -> None:
        """run() returns a dict matching the Schema 3 shape with all required keys."""
        collected = setup_frontier_collected(tmp_path)
        output_path = tmp_path / "frontier-summary.json"

        result = score_frontier.run(
            manifest_path=str(MANIFEST_PATH),
            collected_dir=str(collected),
            output_path=str(output_path),
        )

        for key in _REQUIRED_TOP_KEYS:
            assert key in result, f"Missing top-level key: {key}"

        for mk in _REQUIRED_METADATA_KEYS:
            assert mk in result["_metadata"], f"Missing _metadata key: {mk}"

        for driver_id in score_frontier.DRIVER_IDS:
            assert driver_id in result["driver_scores"], f"Missing driver: {driver_id}"
            ds = result["driver_scores"][driver_id]
            for field in ("score", "level_label", "questions_answered", "questions_total", "confidence"):
                assert field in ds, f"driver_scores[{driver_id}] missing {field}"

        sb = result["scale_breaker"]
        for field in ("driver", "score", "tied_with", "rationale"):
            assert field in sb, f"scale_breaker missing {field}"

        for pid in ("1", "2", "3", "4", "5", "6"):
            assert pid in result["pattern_readiness"], f"Missing pattern {pid}"
            pr = result["pattern_readiness"][pid]
            assert "ready" in pr and "gap_drivers" in pr and "min_gap" in pr

    def test_run_writes_file(self, tmp_path: Path) -> None:
        """run() writes a valid JSON file to output_path containing all required keys."""
        collected = setup_frontier_collected(tmp_path)
        output_path = tmp_path / "frontier-summary.json"

        score_frontier.run(
            manifest_path=str(MANIFEST_PATH),
            collected_dir=str(collected),
            output_path=str(output_path),
        )

        assert output_path.exists()
        content = json.loads(output_path.read_text(encoding="utf-8"))
        for key in _REQUIRED_TOP_KEYS:
            assert key in content, f"Written file missing key: {key}"

    def test_run_high_answers_all_drivers_500(self, tmp_path: Path) -> None:
        """All-yes fixture: every driver scores 500, all 6 patterns ready."""
        collected = setup_frontier_collected(tmp_path, "frontier_answers_high.json")
        output_path = tmp_path / "frontier-summary.json"

        result = score_frontier.run(
            manifest_path=str(MANIFEST_PATH),
            collected_dir=str(collected),
            output_path=str(output_path),
        )

        for driver_id in score_frontier.DRIVER_IDS:
            score = result["driver_scores"][driver_id]["score"]
            label = result["driver_scores"][driver_id]["level_label"]
            assert score == 500, f"Expected score 500 for {driver_id}, got {score}"
            assert label == "Optimized", f"Expected 'Optimized' for {driver_id}, got {label}"

        for pid in ("1", "2", "3", "4", "5", "6"):
            assert result["pattern_readiness"][pid]["ready"] is True, f"Pattern {pid} not ready"

    def test_run_partial_answers_matches_expected_fixture(self, tmp_path: Path) -> None:
        """Partial fixture scores match the pre-generated expected_frontier_scores.json."""
        collected = setup_frontier_collected(tmp_path)
        output_path = tmp_path / "frontier-summary.json"

        result = score_frontier.run(
            manifest_path=str(MANIFEST_PATH),
            collected_dir=str(collected),
            output_path=str(output_path),
        )

        expected = load_fixture("expected_frontier_scores.json")

        # Per-driver score and label match
        for driver_id in score_frontier.DRIVER_IDS:
            actual_score = result["driver_scores"][driver_id]["score"]
            expected_score = expected["driver_scores"][driver_id]["score"]
            assert actual_score == expected_score, (
                f"{driver_id}: expected score {expected_score}, got {actual_score}"
            )
            actual_label = result["driver_scores"][driver_id]["level_label"]
            expected_label = expected["driver_scores"][driver_id]["level_label"]
            assert actual_label == expected_label, (
                f"{driver_id}: expected label '{expected_label}', got '{actual_label}'"
            )

        # Scale-breaker matches
        assert result["scale_breaker"]["driver"] == expected["scale_breaker"]["driver"]
        assert result["scale_breaker"]["score"] == expected["scale_breaker"]["score"]
        assert result["scale_breaker"]["tied_with"] == expected["scale_breaker"]["tied_with"]

        # Pattern 3 is the only ready pattern for this fixture
        assert result["pattern_readiness"]["3"]["ready"] is True
        for pid in ("1", "2", "4", "5", "6"):
            assert result["pattern_readiness"][pid]["ready"] is False, f"Pattern {pid} should not be ready"

    def test_run_missing_frontier_file_degrades_gracefully(self, tmp_path: Path) -> None:
        """run() with no frontier.json in collected dir: all driver scores are 0."""
        collected = tmp_path / "collected"
        collected.mkdir()
        output_path = tmp_path / "frontier-summary.json"

        result = score_frontier.run(
            manifest_path=str(MANIFEST_PATH),
            collected_dir=str(collected),
            output_path=str(output_path),
        )

        for driver_id in score_frontier.DRIVER_IDS:
            assert result["driver_scores"][driver_id]["score"] == 0, (
                f"Expected score 0 for {driver_id} with no answers"
            )

    def test_metadata_block(self, tmp_path: Path) -> None:
        """Output _metadata contains engine_version, a valid timestamp, and manifest_version."""
        collected = setup_frontier_collected(tmp_path)
        output_path = tmp_path / "frontier-summary.json"

        result = score_frontier.run(
            manifest_path=str(MANIFEST_PATH),
            collected_dir=str(collected),
            output_path=str(output_path),
        )

        meta = result["_metadata"]
        assert meta["engine_version"] == score_frontier.ENGINE_VERSION
        assert "T" in meta["timestamp"]  # ISO 8601 contains literal 'T'
        assert meta["manifest_version"] == "1.0.0"


# ---------------------------------------------------------------------------
# TestFrontierEvaluators — Q16 evaluator and framework integration
# ---------------------------------------------------------------------------


def _setup_ppac_collected(tmp_path: Path, fixture_name: str) -> Path:
    """Copy a PPAC fixture into a temp collected/ dir for evaluator testing."""
    collected = tmp_path / "collected"
    collected.mkdir(exist_ok=True)
    data = load_fixture(fixture_name)
    write_json(collected / "ppac.json", data)
    return collected


class TestFrontierEvaluators:
    """Tests for the Q16 evaluator and frontier evaluator framework."""

    def test_evaluator_q16_yes_with_environments(self, tmp_path: Path) -> None:
        """PPAC fixture with 2 envs → evaluator returns ('yes', evidence mentioning both)."""
        collected = _setup_ppac_collected(tmp_path, "ppac_with_envs.json")
        answer, evidence = score_frontier._eval_any_environment_visibility_for_agents(collected)
        assert answer == "yes"
        assert "2 environment(s)" in evidence
        assert "Default" in evidence
        assert "Prod-CoE" in evidence

    def test_evaluator_q16_no_with_empty_environments(self, tmp_path: Path) -> None:
        """PPAC fixture with empty envs list → evaluator returns ('no', evidence)."""
        collected = _setup_ppac_collected(tmp_path, "ppac_empty_envs.json")
        answer, evidence = score_frontier._eval_any_environment_visibility_for_agents(collected)
        assert answer == "no"
        assert "zero environments" in evidence

    def test_evaluator_q16_inconclusive_when_ppac_missing(self, tmp_path: Path) -> None:
        """No ppac.json file → returns (None, evidence about missing)."""
        collected = tmp_path / "collected"
        collected.mkdir()
        answer, evidence = score_frontier._eval_any_environment_visibility_for_agents(collected)
        assert answer is None
        assert "not found" in evidence

    def test_evaluator_q16_inconclusive_when_collector_errored(self, tmp_path: Path) -> None:
        """ppac.json with _metadata.errors populated → returns (None, evidence)."""
        collected = _setup_ppac_collected(tmp_path, "ppac_with_errors.json")
        answer, evidence = score_frontier._eval_any_environment_visibility_for_agents(collected)
        assert answer is None
        assert "collector reported errors" in evidence

    def test_score_driver_facilitator_answer_wins_over_evaluator(
        self, tmp_path: Path, manifest_data: dict
    ) -> None:
        """Facilitator answers 'no' for Q16, but evaluator would return 'yes' → score uses 'no'."""
        collected = _setup_ppac_collected(tmp_path, "ppac_with_envs.json")
        questions = manifest_data["questions"]
        # Facilitator explicitly says "no"
        answers = {"Q16": {"value": "no"}}
        result = score_frontier.score_driver(
            "technology_data", questions, answers, collected_dir=collected
        )
        # L100 ratio should be 0.0 (from "no" = 0.0), not 1.0 (from "yes")
        assert result["level_breakdown"]["100"]["ratio"] == pytest.approx(0.0)

    def test_score_driver_uses_evaluator_when_no_facilitator_answer(
        self, tmp_path: Path, manifest_data: dict
    ) -> None:
        """Facilitator omits Q16, evaluator returns 'yes' → score reflects 'yes'."""
        collected = _setup_ppac_collected(tmp_path, "ppac_with_envs.json")
        questions = manifest_data["questions"]
        answers: dict[str, dict] = {}  # no facilitator answers at all
        result = score_frontier.score_driver(
            "technology_data", questions, answers, collected_dir=collected
        )
        # Q16 is L100 with weight 1.0; evaluator yields "yes" = 1.0
        # Only 1 of 5 tech_data questions answered → ratio at L100 = 1.0
        assert result["level_breakdown"]["100"]["ratio"] == pytest.approx(1.0)
        assert result["questions_answered"] >= 1

    def test_evaluator_coverage_q16_classified_as_auto(self, manifest_data: dict) -> None:
        """After manifest update, coverage matrix counts Q16+Q17+Q13+Q01+Q18+Q03 as auto_evaluable: 6."""
        questions = manifest_data["questions"]
        coverage = score_frontier.compute_evaluator_coverage(questions)
        assert coverage["questions"]["auto_evaluable"] == 6

    def test_run_includes_evaluator_results_in_output(self, tmp_path: Path) -> None:
        """End-to-end via run() populates evaluator_results.Q16 in output JSON."""
        collected = tmp_path / "collected"
        collected.mkdir()
        # Write frontier.json with NO answers (so evaluator kicks in)
        write_json(collected / "frontier.json", {"_metadata": {}, "answers": {}})
        # Write ppac.json with environments
        ppac_data = load_fixture("ppac_with_envs.json")
        write_json(collected / "ppac.json", ppac_data)
        output_path = tmp_path / "frontier-summary.json"

        result = score_frontier.run(
            manifest_path=str(MANIFEST_PATH),
            collected_dir=str(collected),
            output_path=str(output_path),
        )

        assert "evaluator_results" in result
        assert "Q16" in result["evaluator_results"]
        q16_result = result["evaluator_results"]["Q16"]
        assert q16_result["answer_value"] == "yes"
        assert "environment(s)" in q16_result["evidence"]
        assert q16_result["used_for_scoring"] is True


# ---------------------------------------------------------------------------
# TestFrontierQ17Evaluator — Q17 evaluator tests
# ---------------------------------------------------------------------------


def _setup_collected_with(
    tmp_path: Path,
    ppac_fixture: str | None = None,
    sentinel_fixture: str | None = None,
) -> Path:
    """Set up a collected directory with optional PPAC and Sentinel fixtures."""
    collected = tmp_path / "collected"
    collected.mkdir(exist_ok=True)
    if ppac_fixture is not None:
        data = load_fixture(ppac_fixture)
        write_json(collected / "ppac.json", data)
    if sentinel_fixture is not None:
        data = load_fixture(sentinel_fixture)
        write_json(collected / "sentinel.json", data)
    return collected


class TestFrontierQ17Evaluator:
    """Tests for the Q17 evaluator (tagged_environments_with_basic_telemetry)."""

    def test_evaluator_q17_yes_with_tagged_envs_and_sentinel(self, tmp_path: Path) -> None:
        """Tagged envs + Sentinel workspace → ('yes', evidence)."""
        collected = _setup_collected_with(
            tmp_path, "ppac_with_tagged_envs.json", "sentinel_with_workspace.json"
        )
        answer, evidence = score_frontier._eval_tagged_environments_with_basic_telemetry(collected)
        assert answer == "yes"
        assert "2/3 environments with tags" in evidence
        assert "fsi-prod-siem" in evidence

    def test_evaluator_q17_partial_with_tags_but_no_sentinel(self, tmp_path: Path) -> None:
        """Tagged envs but no Sentinel workspace → ('partial', evidence)."""
        collected = _setup_collected_with(
            tmp_path, "ppac_with_tagged_envs.json", "sentinel_no_workspace.json"
        )
        answer, evidence = score_frontier._eval_tagged_environments_with_basic_telemetry(collected)
        assert answer == "partial"
        assert "2/3 environments with tags" in evidence
        assert "Sentinel workspace not found" in evidence

    def test_evaluator_q17_partial_with_sentinel_but_no_tags(self, tmp_path: Path) -> None:
        """No tags/groups but Sentinel workspace present → ('partial', evidence)."""
        collected = _setup_collected_with(
            tmp_path, "ppac_no_tags_no_groups.json", "sentinel_with_workspace.json"
        )
        answer, evidence = score_frontier._eval_tagged_environments_with_basic_telemetry(collected)
        assert answer == "partial"
        assert "0/2 environments with tags" in evidence
        assert "fsi-prod-siem" in evidence

    def test_evaluator_q17_no_when_neither_present(self, tmp_path: Path) -> None:
        """No tags/groups and no Sentinel workspace → ('no', evidence)."""
        collected = _setup_collected_with(
            tmp_path, "ppac_no_tags_no_groups.json", "sentinel_no_workspace.json"
        )
        answer, evidence = score_frontier._eval_tagged_environments_with_basic_telemetry(collected)
        assert answer == "no"
        assert "0/2 environments with tags" in evidence
        assert "Sentinel workspace not found" in evidence

    def test_evaluator_q17_inconclusive_when_ppac_errored(self, tmp_path: Path) -> None:
        """PPAC with collector errors → (None, evidence)."""
        collected = _setup_collected_with(
            tmp_path, "ppac_with_errors.json", "sentinel_with_workspace.json"
        )
        answer, evidence = score_frontier._eval_tagged_environments_with_basic_telemetry(collected)
        assert answer is None
        assert "PPAC data unavailable" in evidence

    def test_evaluator_q17_recognizes_environment_group_membership(self, tmp_path: Path) -> None:
        """Envs with empty Tags but EnvironmentGroupId set + Sentinel → ('yes', group evidence)."""
        collected = _setup_collected_with(
            tmp_path, "ppac_with_env_group.json", "sentinel_with_workspace.json"
        )
        answer, evidence = score_frontier._eval_tagged_environments_with_basic_telemetry(collected)
        assert answer == "yes"
        assert "1 with group membership" in evidence
        assert "1 environment group(s)" in evidence

    def test_score_driver_q17_facilitator_wins_over_evaluator_partial(
        self, tmp_path: Path, manifest_data: dict
    ) -> None:
        """Facilitator says 'yes' while evaluator returns 'partial' → facilitator answer used."""
        collected = _setup_collected_with(
            tmp_path, "ppac_with_tagged_envs.json", "sentinel_no_workspace.json"
        )
        questions = manifest_data["questions"]
        # Facilitator explicitly says "yes" for Q17
        answers = {"Q17": {"value": "yes"}}
        result = score_frontier.score_driver(
            "technology_data", questions, answers, collected_dir=collected
        )
        # L200 ratio should be 1.0 (from facilitator "yes"), not 0.5 (from evaluator "partial")
        assert result["level_breakdown"]["200"]["ratio"] == pytest.approx(1.0)

    def test_evaluator_coverage_q17_classified_as_auto(self, manifest_data: dict) -> None:
        """After manifest update, coverage counts Q16 + Q17 + Q13 + Q01 + Q18 + Q03 as auto_evaluable: 6."""
        questions = manifest_data["questions"]
        coverage = score_frontier.compute_evaluator_coverage(questions)
        # Updated: Q13 + Q01 + Q18 + Q03 are now also auto-evaluable → 6 total.
        assert coverage["questions"]["auto_evaluable"] == 6


# ---------------------------------------------------------------------------
# Helper for Q13 test setup
# ---------------------------------------------------------------------------


def _setup_q13_collected(
    tmp_path: Path,
    ppac_fixture: str | None = None,
    purview_fixture: str | None = None,
) -> Path:
    """Set up a collected directory with optional PPAC and Purview fixtures."""
    collected = tmp_path / "collected"
    collected.mkdir(exist_ok=True)
    if ppac_fixture is not None:
        data = load_fixture(ppac_fixture)
        write_json(collected / "ppac.json", data)
    if purview_fixture is not None:
        data = load_fixture(purview_fixture)
        write_json(collected / "purview.json", data)
    return collected


# ---------------------------------------------------------------------------
# TestFrontierQ13Evaluator — Q13 evaluator tests
# ---------------------------------------------------------------------------


class TestFrontierQ13Evaluator:
    """Tests for the Q13 evaluator (zone_classification_with_audit_supervision_and_model_risk)."""

    def test_evaluator_q13_partial_when_zone_tags_and_audit_present(
        self, tmp_path: Path
    ) -> None:
        """Zone-tagged envs + audit enabled → ('partial', evidence noting model risk)."""
        collected = _setup_q13_collected(
            tmp_path, "ppac_with_zone_tags.json", "purview_with_audit_enabled.json"
        )
        answer, evidence = score_frontier._eval_zone_classification_with_audit_supervision_and_model_risk(collected)
        assert answer == "partial"
        assert "zone-classified environment(s)" in evidence
        assert "audit log enabled" in evidence
        assert "model-risk overlay requires facilitator confirmation" in evidence

    def test_evaluator_q13_partial_when_only_audit_present(
        self, tmp_path: Path
    ) -> None:
        """No zone tags + audit enabled → ('partial', evidence noting zones missing)."""
        collected = _setup_q13_collected(
            tmp_path, "ppac_no_tags_no_groups.json", "purview_with_audit_enabled.json"
        )
        answer, evidence = score_frontier._eval_zone_classification_with_audit_supervision_and_model_risk(collected)
        assert answer == "partial"
        assert "0 zone-classified environment(s)" in evidence
        assert "audit log enabled" in evidence

    def test_evaluator_q13_partial_when_only_zone_tags_present(
        self, tmp_path: Path
    ) -> None:
        """Zone-tagged envs + audit disabled → ('partial', evidence noting audit missing)."""
        collected = _setup_q13_collected(
            tmp_path, "ppac_with_zone_tags.json", "purview_with_audit_disabled.json"
        )
        answer, evidence = score_frontier._eval_zone_classification_with_audit_supervision_and_model_risk(collected)
        assert answer == "partial"
        assert "zone-classified environment(s)" in evidence
        assert "NOT enabled" in evidence

    def test_evaluator_q13_no_when_neither_signal(self, tmp_path: Path) -> None:
        """No zone tags + audit disabled → ('no', evidence)."""
        collected = _setup_q13_collected(
            tmp_path, "ppac_no_tags_no_groups.json", "purview_with_audit_disabled.json"
        )
        answer, evidence = score_frontier._eval_zone_classification_with_audit_supervision_and_model_risk(collected)
        assert answer == "no"
        assert "0 zone-classified environment(s)" in evidence
        assert "NOT enabled" in evidence

    def test_evaluator_q13_inconclusive_when_both_missing(self, tmp_path: Path) -> None:
        """No ppac.json and no purview.json → (None, evidence)."""
        collected = _setup_q13_collected(tmp_path)
        answer, evidence = score_frontier._eval_zone_classification_with_audit_supervision_and_model_risk(collected)
        assert answer is None
        assert "PPAC and Purview data both unavailable" in evidence

    def test_evaluator_q13_inconclusive_when_both_errored(self, tmp_path: Path) -> None:
        """PPAC and Purview both have collector errors → (None, evidence)."""
        collected = _setup_q13_collected(
            tmp_path, "ppac_with_errors.json", "purview_with_errors.json"
        )
        answer, evidence = score_frontier._eval_zone_classification_with_audit_supervision_and_model_risk(collected)
        assert answer is None
        assert "PPAC and Purview data both unavailable" in evidence

    def test_evaluator_q13_recognizes_env_group_zone_naming(self, tmp_path: Path) -> None:
        """Envs with EnvironmentGroupId pointing to 'Production-Zone-2' → zone-classified."""
        collected = _setup_q13_collected(
            tmp_path, "ppac_with_zone_env_group.json", "purview_with_audit_enabled.json"
        )
        answer, evidence = score_frontier._eval_zone_classification_with_audit_supervision_and_model_risk(collected)
        assert answer == "partial"
        assert "zone-classified environment(s)" in evidence
        # Must find at least 1 zone-classified env via group naming.
        assert "0 zone-classified" not in evidence

    def test_evaluator_q13_NEVER_returns_yes(self, tmp_path: Path) -> None:
        """Even with both signals present and zone_count > 0, evaluator returns 'partial' not 'yes'."""
        collected = _setup_q13_collected(
            tmp_path, "ppac_with_zone_tags.json", "purview_with_audit_enabled.json"
        )
        answer, evidence = score_frontier._eval_zone_classification_with_audit_supervision_and_model_risk(collected)
        assert answer != "yes", "Q13 evaluator must NEVER return 'yes' — model risk is not auto-verifiable"
        assert answer == "partial"

    def test_score_driver_q13_facilitator_can_upgrade_to_yes(
        self, tmp_path: Path, manifest_data: dict
    ) -> None:
        """Facilitator says 'yes' while evaluator returns 'partial' → facilitator wins."""
        collected = _setup_q13_collected(
            tmp_path, "ppac_with_zone_tags.json", "purview_with_audit_enabled.json"
        )
        questions = manifest_data["questions"]
        # Facilitator explicitly says "yes" for Q13.
        answers = {"Q13": {"value": "yes"}}
        result = score_frontier.score_driver(
            "ai_governance", questions, answers, collected_dir=collected
        )
        # L300 ratio should be 1.0 (from facilitator "yes"), not 0.5 (from evaluator "partial").
        assert result["level_breakdown"]["300"]["ratio"] == pytest.approx(1.0)

    def test_score_driver_q13_facilitator_can_downgrade_to_no(
        self, tmp_path: Path, manifest_data: dict
    ) -> None:
        """Facilitator says 'no' while evaluator returns 'partial' → facilitator wins."""
        collected = _setup_q13_collected(
            tmp_path, "ppac_with_zone_tags.json", "purview_with_audit_enabled.json"
        )
        questions = manifest_data["questions"]
        # Facilitator explicitly says "no" for Q13.
        answers = {"Q13": {"value": "no"}}
        result = score_frontier.score_driver(
            "ai_governance", questions, answers, collected_dir=collected
        )
        # L300 ratio should be 0.0 (from facilitator "no"), not 0.5 (from evaluator "partial").
        assert result["level_breakdown"]["300"]["ratio"] == pytest.approx(0.0)

    def test_evaluator_coverage_q13_classified_as_auto(self, manifest_data: dict) -> None:
        """After manifest update, coverage shows 6 auto-evaluators (Q16 + Q17 + Q13 + Q01 + Q18 + Q03)."""
        questions = manifest_data["questions"]
        coverage = score_frontier.compute_evaluator_coverage(questions)
        assert coverage["questions"]["auto_evaluable"] == 6


# ---------------------------------------------------------------------------
# TestFrontierQ01Evaluator — Q01 evaluator tests
# ---------------------------------------------------------------------------


def _setup_graph_collected(tmp_path: Path, fixture_name: str) -> Path:
    """Copy a Graph fixture into a temp collected/ dir for evaluator testing."""
    collected = tmp_path / "collected"
    collected.mkdir(exist_ok=True)
    data = load_fixture(fixture_name)
    write_json(collected / "graph.json", data)
    return collected


class TestFrontierQ01Evaluator:
    """Tests for the Q01 evaluator (ai_initiative_owner_identified)."""

    def test_evaluator_q01_yes_with_ai_leadership_titles(self, tmp_path: Path) -> None:
        """Graph fixture with 2 AI-leadership users → ('yes', evidence listing them)."""
        collected = _setup_graph_collected(tmp_path, "graph_with_ai_leadership.json")
        answer, evidence = score_frontier._eval_ai_initiative_owner_identified(collected)
        assert answer == "yes"
        assert "2 user(s)" in evidence
        assert "Jane Doe" in evidence
        assert "Bob Smith" in evidence
        assert "Chief Data Officer" in evidence
        assert "Head of AI" in evidence

    def test_evaluator_q01_partial_with_only_senior_admin_assignments(
        self, tmp_path: Path
    ) -> None:
        """Graph has zero AI titles but Power Platform Admin assigned → ('partial', evidence)."""
        collected = _setup_graph_collected(
            tmp_path, "graph_with_only_admin_assignments.json"
        )
        answer, evidence = score_frontier._eval_ai_initiative_owner_identified(collected)
        assert answer == "partial"
        assert "1 senior platform admin" in evidence
        assert "informal accountability" in evidence

    def test_evaluator_q01_no_with_neither_signal(self, tmp_path: Path) -> None:
        """Graph has no AI titles AND no privileged role assignments → ('no', evidence)."""
        collected = _setup_graph_collected(
            tmp_path, "graph_with_neither_signal.json"
        )
        answer, evidence = score_frontier._eval_ai_initiative_owner_identified(collected)
        assert answer == "no"
        assert "No AI-leadership titles" in evidence

    def test_evaluator_q01_inconclusive_when_graph_missing(self, tmp_path: Path) -> None:
        """No graph.json file → (None, evidence about missing)."""
        collected = tmp_path / "collected"
        collected.mkdir()
        answer, evidence = score_frontier._eval_ai_initiative_owner_identified(collected)
        assert answer is None
        assert "Graph data unavailable" in evidence
        assert "not found" in evidence

    def test_evaluator_q01_inconclusive_when_section7_errored(
        self, tmp_path: Path
    ) -> None:
        """graph.json with aiLeadershipUsers: null AND Section 4 also null → (None, ...)."""
        collected = _setup_graph_collected(
            tmp_path, "graph_with_section7_errored.json"
        )
        answer, evidence = score_frontier._eval_ai_initiative_owner_identified(collected)
        assert answer is None
        assert "Graph data unavailable" in evidence

    def test_evaluator_q01_truncates_long_match_list(self, tmp_path: Path) -> None:
        """Graph fixture with 8 AI-leadership users → evidence shows 3 + 'and 5 more'."""
        collected = _setup_graph_collected(tmp_path, "graph_many_ai_users.json")
        answer, evidence = score_frontier._eval_ai_initiative_owner_identified(collected)
        assert answer == "yes"
        assert "8 user(s)" in evidence
        assert "and 5 more" in evidence

    def test_evaluator_q01_case_insensitive_matching(self, tmp_path: Path) -> None:
        """Graph user with mixed-case jobTitle 'chief data OFFICER' → matched."""
        collected = tmp_path / "collected"
        collected.mkdir(exist_ok=True)
        graph_data = {
            "_metadata": {"collector": "Collect-Graph", "warnings": []},
            "aiLeadershipUsers": [
                {
                    "DisplayName": "Mixed Case User",
                    "UserPrincipalName": "mc@contoso.com",
                    "JobTitle": "chief data OFFICER",
                    "Department": "Data",
                    "MatchedKeyword": ""
                }
            ],
            "privilegedRoleAssignments": [],
        }
        write_json(collected / "graph.json", graph_data)
        answer, evidence = score_frontier._eval_ai_initiative_owner_identified(collected)
        assert answer == "yes"
        assert "Mixed Case User" in evidence

    def test_evaluator_q01_avoids_false_positive_on_word_ai(
        self, tmp_path: Path
    ) -> None:
        """Graph user with jobTitle 'Maintenance Manager' should NOT match."""
        collected = tmp_path / "collected"
        collected.mkdir(exist_ok=True)
        graph_data = {
            "_metadata": {"collector": "Collect-Graph", "warnings": []},
            "aiLeadershipUsers": [
                {
                    "DisplayName": "Maint Worker",
                    "UserPrincipalName": "maint@contoso.com",
                    "JobTitle": "Maintenance Manager",
                    "Department": "Facilities",
                    "MatchedKeyword": ""
                }
            ],
            "privilegedRoleAssignments": [],
        }
        write_json(collected / "graph.json", graph_data)
        answer, evidence = score_frontier._eval_ai_initiative_owner_identified(collected)
        # "Maintenance" contains "ai" but should not match — no valid keyword
        assert answer == "no"
        assert "No AI-leadership titles" in evidence

    def test_score_driver_q01_facilitator_wins_over_evaluator(
        self, tmp_path: Path, manifest_data: dict
    ) -> None:
        """Facilitator answers 'no' while evaluator returns 'yes' → facilitator wins."""
        collected = _setup_graph_collected(
            tmp_path, "graph_with_ai_leadership.json"
        )
        questions = manifest_data["questions"]
        answers = {"Q01": {"value": "no"}}
        result = score_frontier.score_driver(
            "ai_strategy", questions, answers, collected_dir=collected
        )
        # L100 ratio should be 0.0 (from "no"), not 1.0 (from evaluator "yes")
        assert result["level_breakdown"]["100"]["ratio"] == pytest.approx(0.0)

    def test_evaluator_coverage_q01_classified_as_auto(
        self, manifest_data: dict
    ) -> None:
        """After manifest update, coverage shows 6 auto-evaluators (Q16 + Q17 + Q13 + Q01 + Q18 + Q03)."""
        questions = manifest_data["questions"]
        coverage = score_frontier.compute_evaluator_coverage(questions)
        assert coverage["questions"]["auto_evaluable"] == 6


# ---------------------------------------------------------------------------
# TestFrontierQ18Evaluator — Q18 evaluator tests
# ---------------------------------------------------------------------------


def _setup_q18_collected(
    tmp_path: Path,
    ppac_fixture: str | None = None,
    sentinel_fixture: str | None = None,
    sharepoint_fixture: str | None = None,
) -> Path:
    """Copy Q18 fixtures into temp collected/ dir for evaluator testing."""
    collected = tmp_path / "collected"
    collected.mkdir(exist_ok=True)
    if ppac_fixture:
        data = load_fixture(ppac_fixture)
        write_json(collected / "ppac.json", data)
    if sentinel_fixture:
        data = load_fixture(sentinel_fixture)
        write_json(collected / "sentinel.json", data)
    if sharepoint_fixture:
        data = load_fixture(sharepoint_fixture)
        write_json(collected / "sharepoint.json", data)
    return collected


class TestFrontierQ18Evaluator:
    """Tests for the Q18 evaluator (env_groups_with_inventory_siem_rag_and_lineage)."""

    def test_evaluator_q18_partial_when_all_3_signals_present(
        self, tmp_path: Path
    ) -> None:
        """All 3 telemetry signals (env groups, SIEM, SP scan) → ('partial', evidence)."""
        collected = _setup_q18_collected(
            tmp_path,
            "ppac_with_env_group.json",
            "sentinel_with_connector_only.json",
            "sharepoint_with_scan_and_crossref.json",
        )
        answer, evidence = score_frontier._eval_env_groups_with_inventory_siem_rag_and_lineage(collected)
        assert answer == "partial"
        assert "env groups present" in evidence
        assert "SIEM connector(s) enabled" in evidence
        assert "item-level scan ran" in evidence
        assert "agent inventory not collected" in evidence
        assert "RAG-integrity + data lineage require facilitator confirmation" in evidence

    def test_evaluator_q18_partial_when_only_env_groups_present(
        self, tmp_path: Path
    ) -> None:
        """Only env groups signal → ('partial', evidence noting SIEM + SP absent)."""
        collected = _setup_q18_collected(
            tmp_path,
            "ppac_with_env_group.json",
            "sentinel_no_connectors.json",
            "sharepoint_no_scan.json",
        )
        answer, evidence = score_frontier._eval_env_groups_with_inventory_siem_rag_and_lineage(collected)
        assert answer == "partial"
        assert "env groups present" in evidence
        assert "no SIEM connectors enabled" in evidence
        assert "item-level scan absent" in evidence

    def test_evaluator_q18_partial_when_only_siem_present(
        self, tmp_path: Path
    ) -> None:
        """Only SIEM signal → ('partial', evidence noting env groups + SP absent)."""
        collected = _setup_q18_collected(
            tmp_path,
            "ppac_empty_env_groups.json",
            "sentinel_with_connector_only.json",
            "sharepoint_no_scan.json",
        )
        answer, evidence = score_frontier._eval_env_groups_with_inventory_siem_rag_and_lineage(collected)
        assert answer == "partial"
        assert "env groups absent" in evidence
        assert "SIEM connector(s) enabled" in evidence
        assert "item-level scan absent" in evidence

    def test_evaluator_q18_partial_when_only_sp_scan_present(
        self, tmp_path: Path
    ) -> None:
        """Only SP scan signal → ('partial', evidence noting env groups + SIEM absent)."""
        collected = _setup_q18_collected(
            tmp_path,
            "ppac_empty_env_groups.json",
            "sentinel_no_connectors.json",
            "sharepoint_with_scan_and_crossref.json",
        )
        answer, evidence = score_frontier._eval_env_groups_with_inventory_siem_rag_and_lineage(collected)
        assert answer == "partial"
        assert "env groups absent" in evidence
        assert "no SIEM connectors enabled" in evidence
        assert "item-level scan ran" in evidence

    def test_evaluator_q18_no_when_no_signals(self, tmp_path: Path) -> None:
        """Zero telemetry signals → ('no', evidence)."""
        collected = _setup_q18_collected(
            tmp_path,
            "ppac_empty_env_groups.json",
            "sentinel_no_connectors.json",
            "sharepoint_no_scan.json",
        )
        answer, evidence = score_frontier._eval_env_groups_with_inventory_siem_rag_and_lineage(collected)
        assert answer == "no"
        assert "env groups absent" in evidence
        assert "no SIEM connectors enabled" in evidence
        assert "item-level scan absent" in evidence

    def test_evaluator_q18_inconclusive_when_all_sources_missing(
        self, tmp_path: Path
    ) -> None:
        """No ppac.json, sentinel.json, or sharepoint.json → (None, evidence)."""
        collected = _setup_q18_collected(tmp_path)
        answer, evidence = score_frontier._eval_env_groups_with_inventory_siem_rag_and_lineage(collected)
        assert answer is None
        assert "All three data sources unavailable" in evidence

    def test_evaluator_q18_inconclusive_when_all_sources_errored(
        self, tmp_path: Path
    ) -> None:
        """All three collectors have errors → (None, evidence)."""
        collected = _setup_q18_collected(
            tmp_path, "ppac_with_errors.json", "sentinel_no_workspace.json", "sharepoint_errored.json"
        )
        answer, evidence = score_frontier._eval_env_groups_with_inventory_siem_rag_and_lineage(collected)
        assert answer is None
        assert "All three data sources unavailable" in evidence

    def test_evaluator_q18_NEVER_returns_yes(self, tmp_path: Path) -> None:
        """Even with all 3 signals present, evaluator returns 'partial' not 'yes'."""
        collected = _setup_q18_collected(
            tmp_path,
            "ppac_with_env_group.json",
            "sentinel_with_connector_only.json",
            "sharepoint_with_scan_and_crossref.json",
        )
        answer, evidence = score_frontier._eval_env_groups_with_inventory_siem_rag_and_lineage(collected)
        assert answer != "yes", "Q18 evaluator must NEVER return 'yes' — agent inventory + RAG/lineage are not auto-verifiable"
        assert answer == "partial"

    def test_evaluator_q18_evidence_names_missing_signals(self, tmp_path: Path) -> None:
        """Evidence explicitly names which signals are missing."""
        collected = _setup_q18_collected(
            tmp_path,
            "ppac_with_env_group.json",
            "sentinel_no_connectors.json",
            "sharepoint_no_scan.json",
        )
        answer, evidence = score_frontier._eval_env_groups_with_inventory_siem_rag_and_lineage(collected)
        assert answer == "partial"
        assert "no SIEM connectors enabled" in evidence
        assert "item-level scan absent" in evidence

    def test_evaluator_q18_evidence_includes_facilitator_caveats(
        self, tmp_path: Path
    ) -> None:
        """Evidence must mention agent inventory + RAG-integrity + lineage caveats."""
        collected = _setup_q18_collected(
            tmp_path,
            "ppac_with_env_group.json",
            "sentinel_with_connector_only.json",
            "sharepoint_with_scan_and_crossref.json",
        )
        answer, evidence = score_frontier._eval_env_groups_with_inventory_siem_rag_and_lineage(collected)
        assert "agent inventory not collected" in evidence
        assert "RAG-integrity + data lineage require facilitator confirmation" in evidence

    def test_score_driver_q18_facilitator_can_upgrade_to_yes(
        self, tmp_path: Path, manifest_data: dict
    ) -> None:
        """Facilitator says 'yes' while evaluator returns 'partial' → facilitator wins."""
        collected = _setup_q18_collected(
            tmp_path,
            "ppac_with_env_group.json",
            "sentinel_with_connector_only.json",
            "sharepoint_with_scan_and_crossref.json",
        )
        questions = manifest_data["questions"]
        answers = {"Q18": {"value": "yes"}}
        result = score_frontier.score_driver(
            "technology_data", questions, answers, collected_dir=collected
        )
        # L300 ratio should be 1.0 (from facilitator "yes"), not 0.5 (from evaluator "partial")
        assert result["level_breakdown"]["300"]["ratio"] == pytest.approx(1.0)

    def test_score_driver_q18_facilitator_can_downgrade_to_no(
        self, tmp_path: Path, manifest_data: dict
    ) -> None:
        """Facilitator says 'no' while evaluator returns 'partial' → facilitator wins."""
        collected = _setup_q18_collected(
            tmp_path,
            "ppac_with_env_group.json",
            "sentinel_with_connector_only.json",
            "sharepoint_with_scan_and_crossref.json",
        )
        questions = manifest_data["questions"]
        answers = {"Q18": {"value": "no"}}
        result = score_frontier.score_driver(
            "technology_data", questions, answers, collected_dir=collected
        )
        # L300 ratio should be 0.0 (from facilitator "no"), not 0.5 (from evaluator "partial")
        assert result["level_breakdown"]["300"]["ratio"] == pytest.approx(0.0)


# ---------------------------------------------------------------------------
# TestFrontierQ03Evaluator — Q03 evaluator tests
# ---------------------------------------------------------------------------


def _setup_q03_collected(tmp_path: Path, fixture_name: str) -> Path:
    """Copy a SharePoint fixture into temp collected/ dir for Q03 testing."""
    collected = tmp_path / "collected"
    collected.mkdir(exist_ok=True)
    data = load_fixture(fixture_name)
    write_json(collected / "sharepoint.json", data)
    return collected


class TestFrontierQ03Evaluator:
    """Tests for the Q03 evaluator (enterprise_ai_strategy_published_with_portfolio)."""

    def test_evaluator_q03_partial_when_strategy_site_found(
        self, tmp_path: Path
    ) -> None:
        """SharePoint site with AI strategy keyword → ('partial', evidence)."""
        collected = _setup_q03_collected(tmp_path, "sharepoint_with_ai_strategy_site.json")
        answer, evidence = score_frontier._eval_enterprise_ai_strategy_published_with_portfolio(collected)
        assert answer == "partial"
        assert "AI Strategy Council" in evidence
        assert "matched 'ai strategy'" in evidence
        assert "portfolio scope and active governance require facilitator confirmation" in evidence

    def test_evaluator_q03_no_when_no_matching_sites(self, tmp_path: Path) -> None:
        """SharePoint collected but no AI-related site names → ('no', evidence)."""
        collected = _setup_q03_collected(tmp_path, "sharepoint_no_ai_sites.json")
        answer, evidence = score_frontier._eval_enterprise_ai_strategy_published_with_portfolio(collected)
        assert answer == "no"
        assert "No SharePoint site name matched AI strategy/portfolio keywords" in evidence

    def test_evaluator_q03_no_when_empty_inventory(self, tmp_path: Path) -> None:
        """SharePoint collected zero sites → ('no', evidence)."""
        collected = _setup_q03_collected(tmp_path, "sharepoint_empty_inventory.json")
        answer, evidence = score_frontier._eval_enterprise_ai_strategy_published_with_portfolio(collected)
        assert answer == "no"
        assert "SharePoint collected zero sites" in evidence

    def test_evaluator_q03_inconclusive_when_sharepoint_missing(
        self, tmp_path: Path
    ) -> None:
        """No sharepoint.json file → (None, evidence)."""
        collected = tmp_path / "collected"
        collected.mkdir()
        answer, evidence = score_frontier._eval_enterprise_ai_strategy_published_with_portfolio(collected)
        assert answer is None
        assert "SharePoint data unavailable" in evidence
        assert "not found" in evidence

    def test_evaluator_q03_inconclusive_when_sharepoint_errored(
        self, tmp_path: Path
    ) -> None:
        """SharePoint collector reported errors → (None, evidence)."""
        collected = _setup_q03_collected(tmp_path, "sharepoint_errored.json")
        answer, evidence = score_frontier._eval_enterprise_ai_strategy_published_with_portfolio(collected)
        assert answer is None
        assert "SharePoint data unavailable" in evidence
        assert "collector reported errors" in evidence

    def test_evaluator_q03_NEVER_returns_yes(self, tmp_path: Path) -> None:
        """Even with matching site, evaluator returns 'partial' not 'yes'."""
        collected = _setup_q03_collected(tmp_path, "sharepoint_with_ai_strategy_site.json")
        answer, evidence = score_frontier._eval_enterprise_ai_strategy_published_with_portfolio(collected)
        assert answer != "yes", "Q03 evaluator must NEVER return 'yes' — governance review + portfolio scope are facilitator-only"
        assert answer == "partial"

    def test_evaluator_q03_case_insensitive_matching(self, tmp_path: Path) -> None:
        """Site name 'AI GOVERNANCE' (all caps) should match 'ai governance' keyword."""
        collected = tmp_path / "collected"
        collected.mkdir(exist_ok=True)
        sp_data = {
            "_metadata": {"collector": "Collect-SharePoint", "warnings": []},
            "siteInventory": [
                {
                    "Id": "site-3",
                    "DisplayName": "AI GOVERNANCE Portal",
                    "WebUrl": "https://contoso.sharepoint.com/sites/aigovportal",
                    "CreatedDateTime": "2026-05-01T00:00:00Z",
                    "IsPersonalSite": False,
                }
            ],
        }
        write_json(collected / "sharepoint.json", sp_data)
        answer, evidence = score_frontier._eval_enterprise_ai_strategy_published_with_portfolio(collected)
        assert answer == "partial"
        assert "AI GOVERNANCE Portal" in evidence

    def test_evaluator_q03_matches_multiple_keywords(self, tmp_path: Path) -> None:
        """Site name containing both 'ai governance' and 'frontier' matches on first keyword."""
        collected = tmp_path / "collected"
        collected.mkdir(exist_ok=True)
        sp_data = {
            "_metadata": {"collector": "Collect-SharePoint", "warnings": []},
            "siteInventory": [
                {
                    "Id": "site-4",
                    "DisplayName": "AI Governance & Frontier Council",
                    "WebUrl": "https://contoso.sharepoint.com/sites/aigov-frontier",
                    "CreatedDateTime": "2026-05-01T00:00:00Z",
                    "IsPersonalSite": False,
                }
            ],
        }
        write_json(collected / "sharepoint.json", sp_data)
        answer, evidence = score_frontier._eval_enterprise_ai_strategy_published_with_portfolio(collected)
        assert answer == "partial"
        assert "AI Governance & Frontier Council" in evidence

    def test_score_driver_q03_facilitator_can_upgrade_to_yes(
        self, tmp_path: Path, manifest_data: dict
    ) -> None:
        """Facilitator says 'yes' while evaluator returns 'partial' → facilitator wins."""
        collected = _setup_q03_collected(tmp_path, "sharepoint_with_ai_strategy_site.json")
        questions = manifest_data["questions"]
        answers = {"Q03": {"value": "yes"}}
        result = score_frontier.score_driver(
            "ai_strategy", questions, answers, collected_dir=collected
        )
        # L300 ratio should be 1.0 (from facilitator "yes"), not 0.5 (from evaluator "partial")
        assert result["level_breakdown"]["300"]["ratio"] == pytest.approx(1.0)

