/**
 * 31 — Docs render regression suite
 *
 * Guards findings:
 *   F-MERMAID-CDN-BLOCK        — Mermaid JS blocked / missing (unpkg.com not in CSP,
 *                                or loader absent) → raw <pre class="mermaid"> blocks,
 *                                zero SVG output
 *   F-IMAGES-EXCLUDED          — images/ dir excluded from MkDocs build via
 *                                exclude_docs: → "Download diagram" links 404
 *   F-CSP-ORPHAN-LOOSENINGS    — CSP loosenings declared in csp-allowed.json but
 *                                no response was ever loaded from those origins
 *   F-NAVINSTANT-MERMAID-REINIT — Mermaid not re-initialised after Material's
 *                                 navigation.instant SPA-style link navigation
 *   F-DARKMODE-MERMAID         — Mermaid SVG absent when dark palette (slate) active
 *   F-PRINTMODE-MERMAID        — Mermaid SVG absent when print media emulated
 *   F-DEPLOY-COPYRIGHT-PATH    — Footer disclaimer link uses hardcoded
 *                                "/FSI-AgentGov/" subpath, 404s under any
 *                                root-mounted serve (local mkdocs serve /
 *                                Playwright webServer / future re-host)
 *
 * EXPECTED FAILURES ON CURRENT MAIN (pre-fix):
 *   Test 1 — rendered mermaid count 0 ≠ N (Mermaid JS not executing)
 *          — diagram HEAD requests return 404 (exclude_docs: images/)
 *   Test 3 — rendered mermaid absent after navigation.instant click
 *   Test 4 — rendered mermaid absent in dark mode
 *   Test 5 — rendered mermaid absent in print mode
 *   Test 2 / Test 6 — may pass depending on current server state
 *
 * Render detection: Material 9.7.6 renders mermaid into closed shadow DOM
 * (`attachShadow({mode:"closed"})`). `.mermaid svg` returns 0 even on
 * successful render. `countRenderedMermaid` (see _mermaid.mjs) measures
 * `.mermaid` div bounding-box height as the layout-side render signal.
 *
 * Oracle: tests/e2e/fixtures/render-expectations.json
 *   Regenerated by _globalSetup.mjs before every run via
 *   scripts/generate-render-expectations.mjs.
 *   Shape: { pages: { <urlPath>: { source_md, expected_mermaid_count,
 *                                   expected_diagram_links, expected_asset_links } },
 *            summary: {...} }
 *
 * Note on baseURL: playwright.config.mjs sets baseURL to /assessment/.
 * This spec overrides it to the server root so page.goto('/framework/...') works.
 */

import { test } from "@playwright/test";
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { expect } from "./_harness.mjs";
import { countRenderedMermaid } from "./_mermaid.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(here, "../..");

// ── Fixtures ────────────────────────────────────────────────────────────────
const ORACLE = JSON.parse(
  readFileSync(join(here, "fixtures", "render-expectations.json"), "utf8"),
);
const ALLOW = JSON.parse(
  readFileSync(join(here, "fixtures", "csp-allowed.json"), "utf8"),
);
const VERSION = readFileSync(join(REPO_ROOT, "VERSION"), "utf8").trim();

// ── Runtime config ──────────────────────────────────────────────────────────
const PORT = parseInt(process.env.PW_PORT || "8765", 10);
const DOCS_BASE = `http://127.0.0.1:${PORT}`;

// ── CSP allowlist helpers ────────────────────────────────────────────────────
/** Extract HTTP/HTTPS origins from the loosenings fixture (skip keywords). */
function cspAllowedOrigins(allowFixture) {
  const set = new Set();
  for (const entry of allowFixture.loosenings || []) {
    const v = String(entry.value || "");
    if (v.startsWith("http://") || v.startsWith("https://")) {
      try {
        set.add(new URL(v).origin);
      } catch {
        /* skip malformed */
      }
    }
  }
  return set;
}

const CSP_ALLOWED_ORIGINS = cspAllowedOrigins(ALLOW);

/** URL-type loosenings only (not keywords like 'unsafe-inline'). */
const CSP_URL_LOOSENINGS = (ALLOW.loosenings || []).filter((e) => {
  const v = String(e.value || "");
  return v.startsWith("http://") || v.startsWith("https://");
});

// ── Must-cover URL set ───────────────────────────────────────────────────────
// All pages where expected_mermaid_count > 0 OR expected_diagram_links present,
// plus one representative per top-level nav section, plus root and a 404 sentinel.
const MERMAID_PAGES = Object.entries(ORACLE.pages)
  .filter(
    ([, v]) =>
      v.expected_mermaid_count > 0 || v.expected_diagram_links.length > 0,
  )
  .map(([url]) => url);

const REP_PAGES = [
  "/",                                          // Home
  "/getting-started/",                          // Getting Started
  "/framework/",                                // Framework index
  "/controls/pillar-1-security/",               // Controls index
  "/playbooks/",                                // Playbooks index
  "/reference/",                                // Reference index
  "/downloads/",                                // Downloads index
  // ── M2: customer-engagement reference pages (plan-checker MUST-FIX) ──────
  // These pages have no Mermaid and no diagram links so the auto-collected
  // MERMAID_PAGES set excludes them — but they are explicit "key reference
  // materials" customers and CSAs land on. Walk them so any CSP / nav / asset
  // regression is caught.
  "/reference/csa-quick-reference/",
  "/reference/csa-positioning-guide/",
  "/reference/role-catalog/",
  "/reference/regulatory-mappings/",
  "/reference/glossary/",
  // ── AS19b: pre-session ("homework") generated-page sample ─────────────────
  // 147 pre-session pages are generated from a single Jinja template per
  // role (docs/assessment/pre-session/<role-slug>/index.md). The render
  // path, link generation, and slugification all follow the generator,
  // so sampling 5 representative role-shapes catches generator regressions
  // without bloating wall-time. Per AS19 rubber-duck NB3, sample picks
  // distinct role categories + one slug edge-case.
  "/assessment/pre-session/governance-lead/",                                       // canonical high-volume role
  "/assessment/pre-session/compliance-officer/",                                    // compliance role
  "/assessment/pre-session/power-platform-admin/",                                  // admin role
  "/assessment/pre-session/agent-business-owner/",                                  // business / agent role
  "/assessment/pre-session/agent-owner-sponsor-governance-role-not-directory-role/", // long compound slug edge-case
];

const URL_404 = "/this-page-does-not-exist-404/";

const MUST_COVER_URLS = [...new Set([...MERMAID_PAGES, ...REP_PAGES])].sort();

// ── Cross-test state (module-level; safe because fullyParallel=false) ────────
// Test 1 populates; Test 2 reads for orphan detection.
const sharedLoadedOrigins = new Set();

// ── Helpers ──────────────────────────────────────────────────────────────────
function tryOrigin(urlStr) {
  try {
    const o = new URL(urlStr).origin;
    return o === "null" ? null : o;
  } catch {
    return null;
  }
}

const RETRYABLE_HEAD_ERROR_RE =
  /(ECONNREFUSED|ECONNRESET|ERR_CONNECTION_REFUSED|ERR_CONNECTION_RESET)/i;

async function headWithRetry(request, url, attempts = 3) {
  let lastError;
  for (let i = 1; i <= attempts; i++) {
    try {
      return await request.head(url);
    } catch (e) {
      lastError = e;
      const message = String(e?.message || "");
      if (i === attempts || !RETRYABLE_HEAD_ERROR_RE.test(message)) {
        throw e;
      }
      await new Promise((resolve) => setTimeout(resolve, 250 * i));
    }
  }
  throw lastError;
}

/**
 * Install a securitypolicyviolation listener via initScript so it fires on
 * every navigation (including instant-nav) for the lifetime of the page object.
 */
async function installCspCollector(page) {
  await page.addInitScript(() => {
    if (!window.__cspViolations) {
      window.__cspViolations = [];
      document.addEventListener("securitypolicyviolation", (e) => {
        window.__cspViolations.push(
          `${e.violatedDirective}: ${e.blockedURI || "(inline)"}`,
        );
      });
    }
  });
}

/** Drain and reset the CSP violation list from page context. */
async function drainCspViolations(page) {
  return page.evaluate(() => {
    const vs = window.__cspViolations || [];
    window.__cspViolations = [];
    return vs;
  });
}

// ── Override baseURL to site root for all docs tests ────────────────────────
test.use({ baseURL: DOCS_BASE });

// =============================================================================
// Tests are SERIAL (test.describe.serial) because Test 1 populates
// `sharedLoadedOrigins` (module-level Set) and Test 2 reads it for inverse
// orphan detection. If the suite ever flips to parallel workers, Test 2 would
// silently fall back to a 5-page sample and miss orphan loosenings (plan-checker
// feasibility concern F1). Serial wrapping makes the dependency explicit.
test.describe.serial("docs render @regression", () => {
  // ===========================================================================
  // Test 1 — Every page in must-cover set renders correctly
  // ===========================================================================
  test(
    "Every page in must-cover set renders correctly @regression",
    async ({ page, request }) => {
      test.setTimeout(210_000);

      const pageErrors = [];
      const consoleErrors = [];

      // Accumulate response origins for Test 2's orphan check
      page.on("response", (resp) => {
        const o = tryOrigin(resp.url());
        if (o) sharedLoadedOrigins.add(o);
      });

      page.on("pageerror", (err) => {
        pageErrors.push({ url: page.url(), msg: `${err.name}: ${err.message}` });
      });

      page.on("console", (msg) => {
        if (msg.type() !== "error") return;
        // Filter to same-origin only; transient third-party errors (api.github.com
        // rate-limit, etc.) must not redline this local-focus canary.
        const origin = tryOrigin(msg.location()?.url);
        const localOrigin = tryOrigin(page.url());
        if (origin && localOrigin && origin !== localOrigin) return;
        consoleErrors.push({ url: page.url(), msg: msg.text() });
      });

      await installCspCollector(page);

      const failures = [];

      // ── Walk must-cover pages ────────────────────────────────────────────
      for (const urlPath of MUST_COVER_URLS) {
        const absUrl = DOCS_BASE + urlPath;
        const oracle = ORACLE.pages[urlPath];
        const prePageErrorCount = pageErrors.length;
        const preConsoleErrorCount = consoleErrors.length;

        await page.goto(absUrl, { waitUntil: "domcontentloaded" });
        await page.waitForLoadState("networkidle", { timeout: 8_000 }).catch(() => {});

        // (a) Mermaid render — Material renders into closed shadow DOM, so we
        //     measure layout (countRenderedMermaid) instead of `.mermaid svg`.
        //     Polling required because Mermaid processes diagrams asynchronously
        //     after DOMContentLoaded.
        if (oracle && oracle.expected_mermaid_count > 0) {
          try {
            await expect
              .poll(
                () => countRenderedMermaid(page),
                { timeout: 12000 },
              )
              .toBe(oracle.expected_mermaid_count);
          } catch {
            const actual = await countRenderedMermaid(page);
            failures.push(
              `[F-MERMAID-CDN-BLOCK] ${urlPath}: ` +
                `rendered mermaid count ${actual} ≠ expected ${oracle.expected_mermaid_count}`,
            );
          }

          // After Mermaid processes a block it replaces <pre class="mermaid">
          // with <div class="mermaid"><svg>. Any remaining pre.mermaid means
          // the JS runner never fired.
          const preMermaidCount = await page.locator("pre.mermaid").count();
          if (preMermaidCount !== 0) {
            failures.push(
              `[F-MERMAID-CDN-BLOCK] ${urlPath}: ` +
                `${preMermaidCount} raw <pre class="mermaid"> block(s) remain — ` +
                `Mermaid JS not executing`,
            );
          }
        }

        // (b) Diagram download links must return HTTP 200.
        //     Currently fails: exclude_docs: images/ removes the entire tree.
        if (oracle) {
          for (const link of oracle.expected_diagram_links) {
            const absLink = `${DOCS_BASE}/${link}`;
            try {
              const resp = await headWithRetry(request, absLink);
              if (resp.status() !== 200) {
                failures.push(
                  `[F-IMAGES-EXCLUDED] ${urlPath}: ` +
                    `HEAD ${link} → HTTP ${resp.status()} (expected 200)`,
                );
              }
            } catch (e) {
              failures.push(
                `[F-IMAGES-EXCLUDED] ${urlPath}: ` +
                  `HEAD ${link} threw: ${e.message.split("\n")[0]}`,
              );
            }
          }
        }

        // (c) Footer disclaimer link must be path-portable.
        //     [F-DEPLOY-COPYRIGHT-PATH-01] (Phase 3 AS14) The previous
        //     mkdocs.yml `copyright:` field hardcoded
        //     `<a href="/FSI-AgentGov/disclaimer/">` which 404s when the
        //     site is mounted at root. The override at
        //     overrides/partials/copyright.html uses Material's `url`
        //     filter to emit a page-relative href that works at every
        //     mount point.
        {
          const footerHref = await page
            .locator('.md-copyright a[href*="disclaimer"]')
            .first()
            .getAttribute("href");
          if (footerHref === null) {
            failures.push(
              `[F-DEPLOY-COPYRIGHT-PATH-01] ${urlPath}: ` +
                "footer disclaimer link missing from .md-copyright",
            );
          } else if (footerHref.startsWith("/FSI-AgentGov/")) {
            failures.push(
              `[F-DEPLOY-COPYRIGHT-PATH-01] ${urlPath}: ` +
                `footer disclaimer href "${footerHref}" hardcodes ` +
                "site_url subpath — must be page-relative",
            );
          } else {
            const absDisclaimer = new URL(footerHref, page.url()).toString();
            try {
              const resp = await headWithRetry(request, absDisclaimer);
              if (resp.status() !== 200) {
                failures.push(
                  `[F-DEPLOY-COPYRIGHT-PATH-01] ${urlPath}: ` +
                    `footer disclaimer href "${footerHref}" → ` +
                    `HEAD ${absDisclaimer} → HTTP ${resp.status()}`,
                );
              }
            } catch (e) {
              failures.push(
                `[F-DEPLOY-COPYRIGHT-PATH-01] ${urlPath}: ` +
                  `HEAD ${absDisclaimer} threw: ${e.message.split("\n")[0]}`,
              );
            }
          }
        }

        // (d) Page-level zero error counts
        const newPageErrors = pageErrors.slice(prePageErrorCount);
        const newConsoleErrors = consoleErrors.slice(preConsoleErrorCount);
        const cspViolations = await drainCspViolations(page);

        if (newPageErrors.length > 0) {
          failures.push(
            `${urlPath}: ${newPageErrors.length} pageerror(s) — ` +
              `first: ${newPageErrors[0].msg}`,
          );
        }
        if (newConsoleErrors.length > 0) {
          failures.push(
            `${urlPath}: ${newConsoleErrors.length} console.error(s) — ` +
              `first: ${newConsoleErrors[0].msg}`,
          );
        }
        if (cspViolations.length > 0) {
          failures.push(
            `${urlPath}: ${cspViolations.length} CSP violation(s) — ` +
              `first: ${cspViolations[0]}`,
          );
        }
      }

      // ── 404 sentinel — navigate and assert no pageerror crash ───────────
      {
        const pre = pageErrors.length;
        await page.goto(DOCS_BASE + URL_404, { waitUntil: "domcontentloaded" });
        const newErrs = pageErrors.slice(pre);
        if (newErrs.length > 0) {
          failures.push(
            `404 sentinel (${URL_404}): pageerror: ${newErrs[0].msg}`,
          );
        }
      }

      // ── Report all accumulated failures ─────────────────────────────────
      expect(
        failures,
        `Docs render failures (${failures.length} total):\n${failures.join("\n")}`,
      ).toEqual([]);
    },
  );

  // ===========================================================================
  // Test 2 — Inverse CSP orphan detection
  // ===========================================================================
  test(
    "Inverse CSP orphan detection across full crawl @regression",
    async ({ page }) => {
      test.setTimeout(60_000);

      // Use origins accumulated by Test 1 if available; otherwise do a
      // targeted crawl of representative pages to populate the origin set.
      const origins = new Set(sharedLoadedOrigins);

      if (origins.size === 0) {
        page.on("response", (resp) => {
          const o = tryOrigin(resp.url());
          if (o) origins.add(o);
        });
        const samples = [
          "/",
          "/framework/agent-lifecycle/",
          "/controls/pillar-1-security/",
          "/reference/",
          "/assessment/",
        ];
        for (const urlPath of samples) {
          await page.goto(DOCS_BASE + urlPath, {
            waitUntil: "domcontentloaded",
          });
        }
      }

      const serverOrigin = new URL(DOCS_BASE).origin;

      // (a) Every loaded origin must be server or declared in CSP allowlist.
      const unknownOrigins = [];
      for (const origin of origins) {
        if (origin === serverOrigin) continue;
        if (CSP_ALLOWED_ORIGINS.has(origin)) continue;
        unknownOrigins.push(origin);
      }

      expect(
        unknownOrigins,
        [
          "Loaded resources from origins NOT on the CSP allowlist:",
          ...unknownOrigins,
          "",
          "If legitimate, add to overrides/main.html CSP directive AND",
          "tests/e2e/fixtures/csp-allowed.json in the SAME commit with a justification.",
        ].join("\n"),
      ).toEqual([]);

      // (b) [F-CSP-ORPHAN-LOOSENINGS] Every URL-type loosening must be
      //     exercised by ≥1 loaded response. An orphan loosening widens the
      //     attack surface without benefit and should be removed.
      const orphans = [];
      for (const loosening of CSP_URL_LOOSENINGS) {
        let looseningOrigin;
        try {
          looseningOrigin = new URL(loosening.value).origin;
        } catch {
          continue;
        }
        if (!origins.has(looseningOrigin)) {
          orphans.push(
            `[F-CSP-ORPHAN-LOOSENINGS] ${loosening.value} ` +
              `(directive: ${loosening.directive}) — declared in csp-allowed.json ` +
              `but no response was loaded from this origin. ` +
              `Remove from overrides/main.html AND csp-allowed.json in the same commit.`,
          );
        }
      }

      expect(
        orphans,
        `Orphaned CSP loosenings (${orphans.length}):\n${orphans.join("\n")}`,
      ).toEqual([]);
    },
  );

  // ===========================================================================
  // Test 3 — Click-through navigation.instant Mermaid re-init
  // ===========================================================================
  test(
    "Click-through SPA-style navigation re-init (navigation.instant) @regression @smoke",
    async ({ page }) => {
      test.setTimeout(60_000);

      // (a) Start on the Framework index — non-Mermaid, loads Material nav
      await page.goto(DOCS_BASE + "/framework/", {
        waitUntil: "domcontentloaded",
      });

      // (b) Click a deliberately visible user-path link from page content
      //     (preferred over hidden nav tree entries).
      const link = page
        .locator("article.md-content__inner")
        .getByRole("link", { name: /agent lifecycle/i })
        .first();
      await link.waitFor({ state: "visible", timeout: 10_000 });

      // (c) Click the link — NOT page.goto() — to exercise navigation.instant's
      //     SPA-style fetch-and-swap code path.
      await link.click();

      // (d) Wait for URL to change (instant nav updates history via pushState)
      await page.waitForURL(/agent-lifecycle/, { timeout: 15_000 });

      // (e) Mermaid must re-init after instant navigation.
      //     [F-NAVINSTANT-MERMAID-REINIT] — currently fails (0 SVGs)
      await expect
        .poll(() => countRenderedMermaid(page), { timeout: 5_000 })
        .toBeGreaterThan(0);
    },
  );

  // ===========================================================================
  // Test 4 — Dark-mode Mermaid render
  // ===========================================================================
  test(
    "Dark-mode Mermaid render @regression",
    async ({ page }) => {
      test.setTimeout(60_000);

      // Material for MkDocs renders one <input type="radio" name="__palette">
      // per palette entry in mkdocs.yml `theme.palette`. Clicking the radio
      // for the slate palette is the most reliable way to switch — Material
      // wires its own change handler that writes localStorage AND applies
      // `data-md-color-scheme` on the body. Reverse-engineering the
      // localStorage shape and writing it directly is fragile across
      // Material versions.
      // Palette index 1 = the "slate" (dark) scheme defined in mkdocs.yml.

      // Set OS color-scheme preference too so any media-query CSS aligns.
      await page.emulateMedia({ colorScheme: "dark" });

      await page.goto(DOCS_BASE + "/framework/agent-lifecycle/", {
        waitUntil: "domcontentloaded",
      });

      // Click the slate radio (input id="__palette_1"). Material's change
      // handler updates body[data-md-color-scheme] synchronously.
      await page.evaluate(() => {
        const radio = document.getElementById("__palette_1");
        if (!radio) throw new Error("Slate palette radio (#__palette_1) not found");
        radio.click();
      });

      // Wait for Material to apply slate to the body via its change handler.
      await expect
        .poll(
          async () =>
            await page.evaluate(() =>
              document.body.getAttribute("data-md-color-scheme"),
            ),
          { timeout: 5_000, message: "Material did not apply slate palette to body" },
        )
        .toBe("slate");

      const scheme = await page.evaluate(() =>
        document.body.getAttribute("data-md-color-scheme"),
      );
      expect(
        scheme,
        `Dark palette not applied — data-md-color-scheme is "${scheme}", expected "slate"`,
      ).toBe("slate");

      // [F-DARKMODE-MERMAID] Mermaid SVG must render in dark mode.
      // Currently fails because Mermaid JS is not executing at all.
      await expect
        .poll(() => countRenderedMermaid(page), { timeout: 5_000 })
        .toBeGreaterThan(0);
    },
  );

  // ===========================================================================
  // Test 5 — Print-mode Mermaid render survives
  // ===========================================================================
  test(
    "Print-mode Mermaid render survives @regression",
    async ({ page }) => {
      test.setTimeout(60_000);

      await page.emulateMedia({ media: "print" });

      await page.goto(DOCS_BASE + "/framework/agent-lifecycle/", {
        waitUntil: "domcontentloaded",
      });

      // (a) [F-PRINTMODE-MERMAID] SVG must still render when media=print.
      //     Catches the case where someone prints a docs page and diagrams vanish.
      //     Currently fails because Mermaid JS is not executing at all.
      await expect
        .poll(() => countRenderedMermaid(page), { timeout: 5_000 })
        .toBeGreaterThan(0);

      // (b) After successful render no raw <pre class="mermaid"> should remain.
      const preMermaidCount = await page.locator("pre.mermaid").count();
      expect(
        preMermaidCount,
        `${preMermaidCount} unprocessed <pre class="mermaid"> block(s) remain in print mode`,
      ).toBe(0);
    },
  );

  // ===========================================================================
  // Test 6 — version.json shape
  // ===========================================================================
  test("version.json shape @smoke", async ({ request }) => {
    test.setTimeout(30_000);

    const resp = await request.get(`${DOCS_BASE}/version.json`, {
      headers: { "Cache-Control": "no-store" },
    });

    expect(
      resp.status(),
      `version.json returned HTTP ${resp.status()} (expected 200)`,
    ).toBe(200);

    const body = await resp.json();

    // version field must match repo-root VERSION file (single source of truth)
    expect(
      body.version,
      `version.json.version "${body.version}" ≠ VERSION file "${VERSION}"`,
    ).toBe(VERSION);

    // sha must be a 40-char lowercase hex git commit SHA
    expect(
      typeof body.sha === "string" && /^[a-f0-9]{40}$/.test(body.sha),
      `version.json.sha "${body.sha}" is not a 40-char hex commit SHA`,
    ).toBe(true);

    // builtAt must be ISO 8601 (YYYY-MM-DDTHH:MM:SS…)
    expect(
      typeof body.builtAt === "string" &&
        /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/.test(body.builtAt),
      `version.json.builtAt "${body.builtAt}" is not ISO 8601`,
    ).toBe(true);
  });
});

// =============================================================================
// SMOKE — Lightweight 5-page must-cover walk (Phase 4A)
// =============================================================================
//
// Why this exists:
//   Test 1 above ("Every page in must-cover set renders correctly") walks
//   ~30+ pages with full diagram-link HEAD checks + CSP origin tracking and
//   takes ~90s. That is the authoritative regression coverage but is too
//   heavy for the per-PR `e2e-smoke` gate (smoke runtime budget: +90s max
//   per Phase 4A). This test is the smoke-tier counterpart: 5 deterministic,
//   low-churn pages chosen to catch the most common docs regressions in <15s.
//
// Why these 5 pages (chosen for high signal-to-noise on the smoke gate):
//   - "/"                                                    Site root —
//       any catastrophic build failure surfaces here first.
//   - "/framework/agent-lifecycle/"                          Mermaid canary —
//       1 mermaid block per oracle; fastest signal that Mermaid JS execution
//       has regressed (F-MERMAID-CDN-BLOCK / F-NAVINSTANT-MERMAID-REINIT).
//   - "/controls/CONTROL-INDEX/"                             AS13a regression
//       guard — control-index page is the customer entry point to the
//       79-control catalog; if it 404s or pageerrors the catalog is unusable.
//   - "/playbooks/control-implementations/1.1/portal-walkthrough/"
//       Cross-playbook depth-bug guard from AS13a — first standard playbook;
//       proves the 4-playbook-per-control nav pattern still resolves at depth.
//   - "/downloads/"                                          Customer-facing
//       artifact landing — paired with spec 33's downloads-integrity smoke
//       check; this guards the page render, spec 33 guards the file bytes.
//
// What this test deliberately SKIPS (kept in regression Test 1):
//   - HEAD-200 every diagram link (oracle.expected_diagram_links walk)
//   - CSP orphan loosening detection (depends on full crawl populating
//     `sharedLoadedOrigins`)
//   - Mermaid count vs oracle (full oracle-driven assertion)
//   - 404 sentinel
//   - Footer disclaimer href portability check
//
// Smoke is a fast canary: if smoke fails, regression has already failed too.
// This block is intentionally OUTSIDE the test.describe.serial above so it
// has no shared-state coupling to Test 1 / Test 2.
test.describe("docs render smoke @smoke", () => {
  test(
    "@smoke must-cover smoke walk - 5 deterministic pages",
    async ({ page }) => {
      test.setTimeout(15_000);

      // Deterministic, low-churn smoke set. Keep at exactly 5 pages.
      // Any churn here should be reviewed against the rationale above.
      const SMOKE_PAGES = [
        "/",
        "/framework/agent-lifecycle/",
        "/controls/CONTROL-INDEX/",
        "/playbooks/control-implementations/1.1/portal-walkthrough/",
        "/downloads/",
      ];

      const failures = [];

      for (const urlPath of SMOKE_PAGES) {
        const pageErrors = [];
        const consoleErrors = [];

        const errHandler = (err) => {
          pageErrors.push(`${err.name}: ${err.message}`);
        };
        const consoleHandler = (msg) => {
          if (msg.type() !== "error") return;
          // Same-origin filter — third-party errors (api.github.com rate
          // limits etc.) must not redline this local-focus canary.
          // Mirrors the filter logic in regression Test 1.
          const origin = tryOrigin(msg.location()?.url);
          const localOrigin = tryOrigin(page.url());
          if (origin && localOrigin && origin !== localOrigin) return;
          consoleErrors.push(msg.text());
        };

        page.on("pageerror", errHandler);
        page.on("console", consoleHandler);

        try {
          const resp = await page.goto(DOCS_BASE + urlPath, {
            waitUntil: "domcontentloaded",
          });

          const status = resp?.status();
          if (status !== 200) {
            failures.push(`${urlPath}: HTTP ${status} (expected 200)`);
          }

          const title = (await page.title()).trim();
          if (title === "") {
            failures.push(`${urlPath}: <title> is empty`);
          }

          if (pageErrors.length > 0) {
            failures.push(
              `${urlPath}: ${pageErrors.length} pageerror(s) — first: ${pageErrors[0]}`,
            );
          }
          if (consoleErrors.length > 0) {
            failures.push(
              `${urlPath}: ${consoleErrors.length} same-origin console.error(s) — first: ${consoleErrors[0]}`,
            );
          }
        } finally {
          page.off("pageerror", errHandler);
          page.off("console", consoleHandler);
        }
      }

      expect(
        failures,
        `Smoke walk failures (${failures.length}):\n${failures.join("\n")}`,
      ).toEqual([]);
    },
  );
});
