/**
 * 31 — Docs render regression suite
 *
 * Guards findings:
 *   F-MERMAID-CDN-BLOCK        — Mermaid JS blocked / missing (unpkg.com not in CSP,
 *                                or loader absent) → raw <pre class="mermaid"> blocks,
 *                                zero SVG output
 *   F-IMAGES-EXCLUDED          — images/ dir excluded from MkDocs build via
 *                                exclude_docs: → "Download diagram" links 404
 *   F-CSP-ORPHAN-LOOSENINGS    — CSP loosenings declared in csp-allowed.json but
 *                                no response was ever loaded from those origins
 *   F-NAVINSTANT-MERMAID-REINIT — Mermaid not re-initialised after Material's
 *                                 navigation.instant SPA-style link navigation
 *   F-DARKMODE-MERMAID         — Mermaid SVG absent when dark palette (slate) active
 *   F-PRINTMODE-MERMAID        — Mermaid SVG absent when print media emulated
 *
 * EXPECTED FAILURES ON CURRENT MAIN (pre-fix):
 *   Test 1 — .mermaid svg count 0 ≠ N (Mermaid JS not executing)
 *          — diagram HEAD requests return 404 (exclude_docs: images/)
 *   Test 3 — .mermaid svg absent after navigation.instant click
 *   Test 4 — .mermaid svg absent in dark mode
 *   Test 5 — .mermaid svg absent in print mode
 *   Test 2 / Test 6 — may pass depending on current server state
 *
 * Oracle: tests/e2e/fixtures/render-expectations.json
 *   Regenerated by _globalSetup.mjs before every run via
 *   scripts/generate-render-expectations.mjs.
 *   Shape: { pages: { <urlPath>: { source_md, expected_mermaid_count,
 *                                   expected_diagram_links, expected_asset_links } },
 *            summary: {...} }
 *
 * Note on baseURL: playwright.config.mjs sets baseURL to /assessment/.
 * This spec overrides it to the server root so page.goto('/framework/...') works.
 */

import { test } from "@playwright/test";
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { expect } from "./_harness.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(here, "../..");

// ── Fixtures ────────────────────────────────────────────────────────────────
const ORACLE = JSON.parse(
  readFileSync(join(here, "fixtures", "render-expectations.json"), "utf8"),
);
const ALLOW = JSON.parse(
  readFileSync(join(here, "fixtures", "csp-allowed.json"), "utf8"),
);
const VERSION = readFileSync(join(REPO_ROOT, "VERSION"), "utf8").trim();

// ── Runtime config ──────────────────────────────────────────────────────────
const PORT = parseInt(process.env.PW_PORT || "8765", 10);
const DOCS_BASE = `http://127.0.0.1:${PORT}`;

// ── CSP allowlist helpers ────────────────────────────────────────────────────
/** Extract HTTP/HTTPS origins from the loosenings fixture (skip keywords). */
function cspAllowedOrigins(allowFixture) {
  const set = new Set();
  for (const entry of allowFixture.loosenings || []) {
    const v = String(entry.value || "");
    if (v.startsWith("http://") || v.startsWith("https://")) {
      try {
        set.add(new URL(v).origin);
      } catch {
        /* skip malformed */
      }
    }
  }
  return set;
}

const CSP_ALLOWED_ORIGINS = cspAllowedOrigins(ALLOW);

/** URL-type loosenings only (not keywords like 'unsafe-inline'). */
const CSP_URL_LOOSENINGS = (ALLOW.loosenings || []).filter((e) => {
  const v = String(e.value || "");
  return v.startsWith("http://") || v.startsWith("https://");
});

// ── Must-cover URL set ───────────────────────────────────────────────────────
// All pages where expected_mermaid_count > 0 OR expected_diagram_links present,
// plus one representative per top-level nav section, plus root and a 404 sentinel.
const MERMAID_PAGES = Object.entries(ORACLE.pages)
  .filter(
    ([, v]) =>
      v.expected_mermaid_count > 0 || v.expected_diagram_links.length > 0,
  )
  .map(([url]) => url);

const REP_PAGES = [
  "/",                             // Home
  "/getting-started/",             // Getting Started
  "/framework/",                   // Framework index
  "/controls/pillar-1-security/",  // Controls index
  "/playbooks/",                   // Playbooks index
  "/reference/",                   // Reference index
  "/downloads/",                   // Downloads index
];

const URL_404 = "/this-page-does-not-exist-404/";

const MUST_COVER_URLS = [...new Set([...MERMAID_PAGES, ...REP_PAGES])].sort();

// ── Cross-test state (module-level; safe because fullyParallel=false) ────────
// Test 1 populates; Test 2 reads for orphan detection.
const sharedLoadedOrigins = new Set();

// ── Helpers ──────────────────────────────────────────────────────────────────
function tryOrigin(urlStr) {
  try {
    const o = new URL(urlStr).origin;
    return o === "null" ? null : o;
  } catch {
    return null;
  }
}

/**
 * Install a securitypolicyviolation listener via initScript so it fires on
 * every navigation (including instant-nav) for the lifetime of the page object.
 */
async function installCspCollector(page) {
  await page.addInitScript(() => {
    if (!window.__cspViolations) {
      window.__cspViolations = [];
      document.addEventListener("securitypolicyviolation", (e) => {
        window.__cspViolations.push(
          `${e.violatedDirective}: ${e.blockedURI || "(inline)"}`,
        );
      });
    }
  });
}

/** Drain and reset the CSP violation list from page context. */
async function drainCspViolations(page) {
  return page.evaluate(() => {
    const vs = window.__cspViolations || [];
    window.__cspViolations = [];
    return vs;
  });
}

// ── Override baseURL to site root for all docs tests ────────────────────────
test.use({ baseURL: DOCS_BASE });

// =============================================================================
test.describe("docs render @regression", () => {
  // ===========================================================================
  // Test 1 — Every page in must-cover set renders correctly
  // ===========================================================================
  test(
    "Every page in must-cover set renders correctly @regression",
    async ({ page, request }) => {
      test.setTimeout(90_000);

      const pageErrors = [];
      const consoleErrors = [];

      // Accumulate response origins for Test 2's orphan check
      page.on("response", (resp) => {
        const o = tryOrigin(resp.url());
        if (o) sharedLoadedOrigins.add(o);
      });

      page.on("pageerror", (err) => {
        pageErrors.push({ url: page.url(), msg: `${err.name}: ${err.message}` });
      });

      page.on("console", (msg) => {
        if (msg.type() !== "error") return;
        // Filter to same-origin only; transient third-party errors (api.github.com
        // rate-limit, etc.) must not redline this local-focus canary.
        const origin = tryOrigin(msg.location()?.url);
        const localOrigin = tryOrigin(page.url());
        if (origin && localOrigin && origin !== localOrigin) return;
        consoleErrors.push({ url: page.url(), msg: msg.text() });
      });

      await installCspCollector(page);

      const failures = [];

      // ── Walk must-cover pages ────────────────────────────────────────────
      for (const urlPath of MUST_COVER_URLS) {
        const absUrl = DOCS_BASE + urlPath;
        const oracle = ORACLE.pages[urlPath];
        const prePageErrorCount = pageErrors.length;
        const preConsoleErrorCount = consoleErrors.length;

        await page.goto(absUrl, { waitUntil: "domcontentloaded" });

        // (a) Mermaid SVG count — polling required because Mermaid processes
        //     diagrams asynchronously after DOMContentLoaded.
        if (oracle && oracle.expected_mermaid_count > 0) {
          try {
            await expect
              .poll(
                () => page.locator(".mermaid svg").count(),
                { timeout: 2000 },
              )
              .toBe(oracle.expected_mermaid_count);
          } catch {
            const actual = await page.locator(".mermaid svg").count();
            failures.push(
              `[F-MERMAID-CDN-BLOCK] ${urlPath}: ` +
                `.mermaid svg count ${actual} ≠ expected ${oracle.expected_mermaid_count}`,
            );
          }

          // After Mermaid processes a block it replaces <pre class="mermaid">
          // with <div class="mermaid"><svg>. Any remaining pre.mermaid means
          // the JS runner never fired.
          const preMermaidCount = await page.locator("pre.mermaid").count();
          if (preMermaidCount !== 0) {
            failures.push(
              `[F-MERMAID-CDN-BLOCK] ${urlPath}: ` +
                `${preMermaidCount} raw <pre class="mermaid"> block(s) remain — ` +
                `Mermaid JS not executing`,
            );
          }
        }

        // (b) Diagram download links must return HTTP 200.
        //     Currently fails: exclude_docs: images/ removes the entire tree.
        if (oracle) {
          for (const link of oracle.expected_diagram_links) {
            const absLink = `${DOCS_BASE}/${link}`;
            try {
              const resp = await request.head(absLink);
              if (resp.status() !== 200) {
                failures.push(
                  `[F-IMAGES-EXCLUDED] ${urlPath}: ` +
                    `HEAD ${link} → HTTP ${resp.status()} (expected 200)`,
                );
              }
            } catch (e) {
              failures.push(
                `[F-IMAGES-EXCLUDED] ${urlPath}: ` +
                  `HEAD ${link} threw: ${e.message.split("\n")[0]}`,
              );
            }
          }
        }

        // (c) Page-level zero error counts
        const newPageErrors = pageErrors.slice(prePageErrorCount);
        const newConsoleErrors = consoleErrors.slice(preConsoleErrorCount);
        const cspViolations = await drainCspViolations(page);

        if (newPageErrors.length > 0) {
          failures.push(
            `${urlPath}: ${newPageErrors.length} pageerror(s) — ` +
              `first: ${newPageErrors[0].msg}`,
          );
        }
        if (newConsoleErrors.length > 0) {
          failures.push(
            `${urlPath}: ${newConsoleErrors.length} console.error(s) — ` +
              `first: ${newConsoleErrors[0].msg}`,
          );
        }
        if (cspViolations.length > 0) {
          failures.push(
            `${urlPath}: ${cspViolations.length} CSP violation(s) — ` +
              `first: ${cspViolations[0]}`,
          );
        }
      }

      // ── 404 sentinel — navigate and assert no pageerror crash ───────────
      {
        const pre = pageErrors.length;
        await page.goto(DOCS_BASE + URL_404, { waitUntil: "domcontentloaded" });
        const newErrs = pageErrors.slice(pre);
        if (newErrs.length > 0) {
          failures.push(
            `404 sentinel (${URL_404}): pageerror: ${newErrs[0].msg}`,
          );
        }
      }

      // ── Report all accumulated failures ─────────────────────────────────
      expect(
        failures,
        `Docs render failures (${failures.length} total):\n${failures.join("\n")}`,
      ).toEqual([]);
    },
  );

  // ===========================================================================
  // Test 2 — Inverse CSP orphan detection
  // ===========================================================================
  test(
    "Inverse CSP orphan detection across full crawl @regression",
    async ({ page }) => {
      test.setTimeout(60_000);

      // Use origins accumulated by Test 1 if available; otherwise do a
      // targeted crawl of representative pages to populate the origin set.
      const origins = new Set(sharedLoadedOrigins);

      if (origins.size === 0) {
        page.on("response", (resp) => {
          const o = tryOrigin(resp.url());
          if (o) origins.add(o);
        });
        const samples = [
          "/",
          "/framework/agent-lifecycle/",
          "/controls/pillar-1-security/",
          "/reference/",
          "/assessment/",
        ];
        for (const urlPath of samples) {
          await page.goto(DOCS_BASE + urlPath, {
            waitUntil: "domcontentloaded",
          });
        }
      }

      const serverOrigin = new URL(DOCS_BASE).origin;

      // (a) Every loaded origin must be server or declared in CSP allowlist.
      const unknownOrigins = [];
      for (const origin of origins) {
        if (origin === serverOrigin) continue;
        if (CSP_ALLOWED_ORIGINS.has(origin)) continue;
        unknownOrigins.push(origin);
      }

      expect(
        unknownOrigins,
        [
          "Loaded resources from origins NOT on the CSP allowlist:",
          ...unknownOrigins,
          "",
          "If legitimate, add to overrides/main.html CSP directive AND",
          "tests/e2e/fixtures/csp-allowed.json in the SAME commit with a justification.",
        ].join("\n"),
      ).toEqual([]);

      // (b) [F-CSP-ORPHAN-LOOSENINGS] Every URL-type loosening must be
      //     exercised by ≥1 loaded response. An orphan loosening widens the
      //     attack surface without benefit and should be removed.
      const orphans = [];
      for (const loosening of CSP_URL_LOOSENINGS) {
        let looseningOrigin;
        try {
          looseningOrigin = new URL(loosening.value).origin;
        } catch {
          continue;
        }
        if (!origins.has(looseningOrigin)) {
          orphans.push(
            `[F-CSP-ORPHAN-LOOSENINGS] ${loosening.value} ` +
              `(directive: ${loosening.directive}) — declared in csp-allowed.json ` +
              `but no response was loaded from this origin. ` +
              `Remove from overrides/main.html AND csp-allowed.json in the same commit.`,
          );
        }
      }

      expect(
        orphans,
        `Orphaned CSP loosenings (${orphans.length}):\n${orphans.join("\n")}`,
      ).toEqual([]);
    },
  );

  // ===========================================================================
  // Test 3 — Click-through navigation.instant Mermaid re-init
  // ===========================================================================
  test(
    "Click-through SPA-style navigation re-init (navigation.instant) @regression",
    async ({ page }) => {
      test.setTimeout(60_000);

      // (a) Start on the Framework index — non-Mermaid, loads Material nav
      await page.goto(DOCS_BASE + "/framework/", {
        waitUntil: "domcontentloaded",
      });

      // (b) Locate a link to the agent-lifecycle page (oracle: 1 mermaid block).
      //     Material renders nav links as <a href="/framework/agent-lifecycle/">.
      const targetSuffix = "/framework/agent-lifecycle/";
      const link = page
        .locator(`a[href$="${targetSuffix}"]`)
        .first();
      await link.waitFor({ timeout: 10_000 });

      // (c) Click the link — NOT page.goto() — to exercise navigation.instant's
      //     SPA-style fetch-and-swap code path.
      await link.click();

      // (d) Wait for URL to change (instant nav updates history via pushState)
      await page.waitForURL(/agent-lifecycle/, { timeout: 15_000 });

      // (e) Mermaid must re-init after instant navigation.
      //     [F-NAVINSTANT-MERMAID-REINIT] — currently fails (0 SVGs)
      await expect
        .poll(() => page.locator(".mermaid svg").count(), { timeout: 5_000 })
        .toBeGreaterThan(0);
    },
  );

  // ===========================================================================
  // Test 4 — Dark-mode Mermaid render
  // ===========================================================================
  test(
    "Dark-mode Mermaid render @regression",
    async ({ page }) => {
      test.setTimeout(60_000);

      // Material for MkDocs reads __palette from localStorage on page init.
      // Palette index 1 = the "slate" (dark) scheme defined in mkdocs.yml.
      // Seed before first navigation so Material applies the scheme immediately.
      await page.addInitScript(() => {
        localStorage.setItem("__palette", JSON.stringify({ index: 1 }));
      });

      // Also set the OS color-scheme preference so media queries align.
      await page.emulateMedia({ colorScheme: "dark" });

      await page.goto(DOCS_BASE + "/framework/agent-lifecycle/", {
        waitUntil: "domcontentloaded",
      });

      // Assert dark scheme was applied to the document
      const scheme = await page.evaluate(() =>
        document.body.getAttribute("data-md-color-scheme"),
      );
      expect(
        scheme,
        `Dark palette not applied — data-md-color-scheme is "${scheme}", expected "slate"`,
      ).toBe("slate");

      // [F-DARKMODE-MERMAID] Mermaid SVG must render in dark mode.
      // Currently fails because Mermaid JS is not executing at all.
      await expect
        .poll(() => page.locator(".mermaid svg").count(), { timeout: 5_000 })
        .toBeGreaterThan(0);
    },
  );

  // ===========================================================================
  // Test 5 — Print-mode Mermaid render survives
  // ===========================================================================
  test(
    "Print-mode Mermaid render survives @regression",
    async ({ page }) => {
      test.setTimeout(60_000);

      await page.emulateMedia({ media: "print" });

      await page.goto(DOCS_BASE + "/framework/agent-lifecycle/", {
        waitUntil: "domcontentloaded",
      });

      // (a) [F-PRINTMODE-MERMAID] SVG must still render when media=print.
      //     Catches the case where someone prints a docs page and diagrams vanish.
      //     Currently fails because Mermaid JS is not executing at all.
      await expect
        .poll(() => page.locator(".mermaid svg").count(), { timeout: 5_000 })
        .toBeGreaterThan(0);

      // (b) After successful render no raw <pre class="mermaid"> should remain.
      const preMermaidCount = await page.locator("pre.mermaid").count();
      expect(
        preMermaidCount,
        `${preMermaidCount} unprocessed <pre class="mermaid"> block(s) remain in print mode`,
      ).toBe(0);
    },
  );

  // ===========================================================================
  // Test 6 — version.json shape
  // ===========================================================================
  test("version.json shape @smoke", async ({ request }) => {
    test.setTimeout(30_000);

    const resp = await request.get(`${DOCS_BASE}/version.json`, {
      headers: { "Cache-Control": "no-store" },
    });

    expect(
      resp.status(),
      `version.json returned HTTP ${resp.status()} (expected 200)`,
    ).toBe(200);

    const body = await resp.json();

    // version field must match repo-root VERSION file (single source of truth)
    expect(
      body.version,
      `version.json.version "${body.version}" ≠ VERSION file "${VERSION}"`,
    ).toBe(VERSION);

    // sha must be a 40-char lowercase hex git commit SHA
    expect(
      typeof body.sha === "string" && /^[a-f0-9]{40}$/.test(body.sha),
      `version.json.sha "${body.sha}" is not a 40-char hex commit SHA`,
    ).toBe(true);

    // builtAt must be ISO 8601 (YYYY-MM-DDTHH:MM:SS…)
    expect(
      typeof body.builtAt === "string" &&
        /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/.test(body.builtAt),
      `version.json.builtAt "${body.builtAt}" is not ISO 8601`,
    ).toBe(true);
  });
});
